// SciMath Battle flashcard data.
// Sources: DOST Caraga SciMath Battle 2025 round slides (Easy, Average, Difficult)
// and the "SciMath Battle 2026 Reviewer (Grade 6)".
// Fields: q = question, c = choices, a = answer, e = how to get it, m = memory trick.

window.GROUPS = [
  { id: "real", name: "Real 2025 contest", note: "The actual questions from July 30, 2025. Start here." },
  { id: "twist", name: "Possible twists", note: "The 2025 questions with new numbers or a flipped ask." },
  { id: "p26", name: "2026-style practice", note: "New questions at the real contest level." },
  { id: "memo", name: "Memory sheet", note: "Must-remember facts. Read aloud once a day." },
  { id: "math", name: "Math warm-ups", note: "Easier basics, then challenge and tie-breakers. Use π = 22/7." },
  { id: "sci", name: "Science warm-ups", note: "Easier basics, then challenge and tie-breakers." },
  { id: "tech", name: "Tech & STEM", note: "Acronyms, inventors, Filipino scientists, Caraga places." }
];

window.DECKS = [
  { id: "e25", group: "real", name: "Easy round", round: "easy", pts: 1, time: 15 },
  { id: "a25", group: "real", name: "Average round", round: "average", pts: 2, time: 30 },
  { id: "d25", group: "real", name: "Difficult round", round: "difficult", pts: 3, time: 60 },
  { id: "et", group: "twist", name: "Easy twists", round: "easy", pts: 1, time: 15 },
  { id: "at", group: "twist", name: "Average twists", round: "average", pts: 2, time: 30 },
  { id: "dt", group: "twist", name: "Difficult twists", round: "difficult", pts: 3, time: 60 },
  { id: "ep", group: "p26", name: "Easy style", round: "easy", pts: 1, time: 15 },
  { id: "ap", group: "p26", name: "Average style", round: "average", pts: 2, time: 30 },
  { id: "dp", group: "p26", name: "Difficult style", round: "difficult", pts: 3, time: 60 },
  { id: "mem", group: "memo", name: "Memory sheet", round: "memo", time: 30 },
  { id: "ml1", group: "math", name: "Level 1 · quick facts", round: "warm", time: 15 },
  { id: "ml2", group: "math", name: "Level 2 · word problems", round: "warm", time: 30 },
  { id: "ml3", group: "math", name: "Level 3 · challenge", round: "warm", time: 60 },
  { id: "mcl", group: "math", name: "Clinchers", round: "warm", time: 60 },
  { id: "frm", group: "math", name: "Formula sheet", round: "warm", time: 15 },
  { id: "sl1", group: "sci", name: "Level 1 · quick facts", round: "warm", time: 15 },
  { id: "sl2", group: "sci", name: "Level 2 · understanding", round: "warm", time: 15 },
  { id: "sl3", group: "sci", name: "Level 3 · challenge", round: "warm", time: 30 },
  { id: "scl", group: "sci", name: "Clinchers", round: "warm", time: 30 },
  { id: "tch", group: "tech", name: "Tech & STEM", round: "warm", time: 15 }
];

window.CARDS = {
  e25: [
    { cat: "Physics", q: "Pan Zhanle of China set a record of 46.40 s in the 100 m freestyle at the 2024 Paris Olympics. He swims a 50-meter pool there and back. What are his displacement and distance?",
      c: ["Both zero", "100 m displacement, 0 distance", "0 m displacement, 100 m distance", "100 m displacement, 100 m distance"],
      a: "C · 0 m displacement, 100 m distance",
      e: "Like walking to the store and back home. You walked 100 m (distance), but you ended at home, so you are 0 m from the start (displacement).",
      m: "Go and come back = displacement 0." },
    { cat: "Astronomy", q: "Kepler's Second Law: a line from the Sun to a planet sweeps equal areas in equal times. At which point in Earth's orbit does it move fastest?",
      c: ["Aphelion", "Apogee", "Perigee", "Perihelion"],
      a: "D · Perihelion",
      e: "Earth runs fastest when it is nearest the Sun.",
      m: "Peri = near. Helion = Sun. Perihelion = near the Sun." },
    { cat: "Geometry", q: "A triangular prism has a right-triangle base with legs 3 cm and 4 cm. Its volume is 60 cm³. What is the height of the prism?",
      a: "10 cm",
      e: "Triangle floor: 3 × 4 = 12, then half = 6. Then 6 × what = 60? Answer: 10.",
      m: "Half, then times height." },
    { cat: "Chemistry", q: "If two objects are in thermal equilibrium with each other, they cannot…",
      c: ["be moving", "be undergoing an elastic collision", "have different pressures", "be at different temperatures"],
      a: "D · be at different temperatures",
      e: "Put a cold spoon in hot soup. After a while both are the same warmth. Equilibrium means the same temperature.",
      m: "Cold spoon in hot soup." },
    { cat: "Ratio", q: "Three numbers are in the ratio 2:3:5. Their product is 810. What is the largest number?",
      a: "15",
      e: "2 × 3 × 5 = 30. 810 ÷ 30 = 27 = 3 × 3 × 3. Multiply each by 3: 6, 9, 15. Check: 6 × 9 × 15 = 810." },
    { cat: "Ratio", q: "A square pyramid and a cube have equal base areas. If their volumes are equal, what is the ratio of the height of the pyramid to the height of the cube?",
      a: "3:1",
      e: "A pyramid is pointy, so it holds only 1/3 of a box. To hold the same amount it must be 3 times as tall.",
      m: "Pointy shapes hold 1/3." },
    { cat: "Biology", q: "Compared to an artery, the wall of a vein differs in which way?",
      c: ["It consists of three coats called tunics", "It is lined by a thin layer of endothelium", "It contains smooth muscle", "The middle tunic is thin"],
      a: "D · The middle tunic is thin",
      e: "Arteries push blood hard, like a hose at full blast, so they need thick walls. Veins carry slow blood, so their middle wall is thin.",
      m: "A for Artery, A for Away (and thick)." },
    { cat: "Fractions", q: "Therese had 2 1/2 pizzas. She gave 3/4 of a pizza to her brother and 2/3 of a pizza to her cousin. How much pizza is left?",
      a: "13/12 or 1 1/12",
      e: "Cut every pizza into 12 slices. 2 1/2 pizzas = 30 slices. Brother gets 9, cousin gets 8. 30 − 9 − 8 = 13 slices = 1 whole pizza and 1 slice." },
    { cat: "Physics", q: "The distance between one point of a wave and the exact same place on the next cycle of the wave.",
      c: ["Amplitude", "Crest", "Expansion", "Wavelength"],
      a: "D · Wavelength",
      e: "Wavelength = from one wave top to the next wave top, like the space between two humps." },
    { cat: "Geometry", q: "A cube with a volume of 64 cubic units is painted, then sliced into unit cubes. How many unit cubes have three sides painted?",
      a: "8",
      e: "64 = 4 × 4 × 4. Only corner pieces have 3 painted sides. A box has 8 corners.",
      m: "Corners = always 8." }
  ],
  a25: [
    { cat: "Ratio & proportion", q: "Divine's allowance was increased by 25% while Faith's was decreased by 25%. Now their allowances are equal. What is the ratio of Divine's original allowance to Faith's original allowance?",
      a: "3:5",
      e: "Try numbers. Divine ₱300 + 25% (₱75) = ₱375. Faith ₱500 − 25% (₱125) = ₱375. Equal! So 300 : 500 = 3 : 5.",
      m: "The one who got the raise started smaller." },
    { cat: "Chemistry", q: "TRUE or FALSE: Water can be solid, liquid, and gas at the same time.",
      a: "TRUE",
      e: "At one special cold temperature with very low air pressure (the triple point), ice, water, and steam can all exist together." },
    { cat: "Physics", q: "For a wave travelling at a constant velocity, what happens to the wavelength if the frequency is doubled?",
      c: ["It will be halved", "It will also be doubled", "It will stay constant", "It will increase by a factor of 4"],
      a: "A · It will be halved",
      e: "Shake a jump rope faster and you get more waves, but each wave gets shorter. Twice as many waves = each is half as long.",
      m: "Shake a jump rope faster." },
    { cat: "Equations", q: "In a math quiz, Bong answered 7 questions. He gained 4 points for each correct answer and lost 3 points for each incorrect one. His total was 7. How many did he answer correctly?",
      a: "4",
      e: "Try 4 right: 4 × 4 = 16. That leaves 3 wrong: 3 × 3 = 9 lost. 16 − 9 = 7. Correct!",
      m: "Guess, check, adjust." },
    { cat: "Numbers", q: "There are 6 consecutive even numbers. The largest is two times the smallest. What is the second largest number?",
      a: "18",
      e: "Six even numbers in a row: the biggest is always 10 more than the smallest. Try 10: 10, 12, 14, 16, 18, 20. Is 20 double 10? Yes! Second biggest = 18." },
    { cat: "Earth science", q: "A magnitude-5.5 earthquake struck Lingig, Surigao del Sur on July 20, 2025. What does magnitude measure and how is it related to intensity?",
      c: ["Intensity measures effects on the surface, structures, and people; magnitude measures the damage to the community and livelihood",
          "Magnitude measures the energy released at the source; intensity measures the strength of shaking at a specific location",
          "Magnitude measures the energy released at the source, and intensity is the same as magnitude",
          "Intensity depends on distance, soil, and buildings; magnitude depends only on local soil"],
      a: "B · Magnitude = energy released at the source; intensity = strength of shaking at a place",
      e: "Magnitude = how strong the quake is where it started (only one number). Intensity = how strong it feels where you are.",
      m: "Like a speaker: loud up close, soft far away." },
    { cat: "Biology", q: "Systemic arterial blood pressure is most often measured in this artery, using a stethoscope and sphygmomanometer.",
      c: ["Aorta", "Brachial artery", "Carotid artery", "Femoral artery"],
      a: "B · Brachial artery",
      e: "When a nurse checks blood pressure, the cuff goes on your upper arm. That artery is the brachial artery.",
      m: "Brachial = arm." },
    { cat: "LCM", q: "Three signal lights flash every 12, 30, and 66 seconds. They flash together at 8:30 AM. At what time will they next flash together?",
      a: "8:41 AM",
      e: "Find the smallest number all three go into (LCM): 660 seconds = 11 minutes. 8:30 + 11 minutes = 8:41 AM. (The official slide printed PM by mistake.)",
      m: "Together again = LCM. Watch AM and PM!" },
    { cat: "Prime numbers", q: "The product of three prime numbers was added to 1 and the result was 1222. What is the sum of these prime numbers?",
      a: "51",
      e: "Take away the 1: 1221. 1221 ÷ 3 = 407, then 407 ÷ 11 = 37. So 3 + 11 + 37 = 51.",
      m: "Test primes in order: 2, 3, 5, 7, 11, 13…" },
    { cat: "Biology", q: "A graph shows sugar eaten and number of cavities for different countries (one dot per country). The dots go up together. Which statement does the graph support?",
      c: ["In some countries, people brush their teeth more often than in others", "The more sugar people eat, the more likely they are to get cavities", "In recent years, cavities have increased in many countries", "In recent years, sugar consumption has increased in many countries"],
      a: "B · More sugar, more likely to get cavities",
      e: "Only choose what the graph shows. Dots go up = more sugar, more cavities. The graph says nothing about brushing or years." }
  ],
  d25: [
    { cat: "Earth science", q: "The Philippines has cooler temperatures and strong amihan winds, which often affect farming schedules and harvests. Identify the season.",
      a: "Dry season (the cool dry part, December to February)",
      e: "Amihan = cold wind (December to February). Habagat = rainy wind. Cold and not rainy = dry season.",
      m: "Amihan = lamig (cold). Habagat = basa (wet)." },
    { cat: "Astronomy", q: "This small cluster of stars, called “Moroporo” by ancient Filipinos, was believed to signal the start of the rainy season. What is its modern name?",
      a: "Pleiades",
      e: "Just memorize: Moroporo = Pleiades, also called the Seven Sisters.",
      m: "Moroporo = small cluster of 7 = Seven Sisters." },
    { cat: "Discounts", q: "13 people celebrated at a restaurant. Four were senior citizens. The bill was ₱4,209 after the 20% senior discount. How much did each senior citizen pay?",
      a: "₱276",
      e: "A senior pays 8/10 of a meal, so 4 seniors = 3.2 meals. Total = 9 + 3.2 = 12.2 meals. One meal = 4,209 ÷ 12.2 = ₱345. Senior pays 345 − 69 = ₱276.",
      m: "A senior counts as 0.8 of a person." },
    { cat: "Chemistry", q: "Sheen mixes flour, water, salt, and yeast, then lets the dough rest. Yeast turns the starch and sugars into carbon dioxide and alcohol, so the dough rises. What is this process?",
      a: "Fermentation",
      e: "Yeast is a tiny living thing that “eats” sugar and makes gas bubbles. The bubbles puff up the bread." },
    { cat: "Percentage", q: "Mae needs a 12% acid solution. The lab only has 20 liters of 15% acid solution. How many liters of water should she add?",
      a: "5 L",
      e: "Pure acid: 15% of 20 L = 3 L. Water does not change this 3 L. 12% of what = 3? 12% of 25 = 3. Total must be 25 L. 25 − 20 = add 5 L.",
      m: "Adding water never changes the pure part. Find it first." },
    { cat: "Biology", q: "Scientists must quickly grow many genetically identical plants of a rare seedless banana that cannot reproduce sexually. What method should they use?",
      a: "Vegetative (asexual) reproduction",
      e: "No seeds, so use plant parts (like banana suckers) to grow new plants. The new plants are exact copies." },
    { cat: "Motion", q: "Daisy walks from her house toward Von's at 60 m/min. At the same time Von walks toward Daisy's at 90 m/min. They meet 20 m from the midpoint. How far apart are the houses?",
      a: "200 m",
      e: "Von is faster, so he passes the middle by 20 m and Daisy is 20 m short. Von walks 40 m more. He gains 30 m each minute, so it takes 1 1/3 minutes. Daisy 80 m + Von 120 m = 200 m.",
      m: "Faster one walks 2 × (distance from midpoint) extra." },
    { cat: "Waves & sound", q: "At a concert, people hear echoes that make the music unclear. What wave behavior causes this?",
      a: "Reflection (sound reflection)",
      e: "An echo is sound bouncing back from a wall. Bouncing back = reflection.",
      m: "Reflect = return. Refract = bend." },
    { cat: "Counting", q: "What is the sum of all 4-digit numbers containing the digits 1, 3, 4, and 7 (each used once)?",
      a: "99,990",
      e: "There are 24 such numbers. Each digit sits in each place 6 times. 1 + 3 + 4 + 7 = 15. 15 × 6 = 90. 90 × 1,111 = 99,990.",
      m: "4 digits: sum × 6 × 1,111. 3 digits: sum × 2 × 111." },
    { cat: "Biology", q: "A pregnant woman has an ultrasound showing no pregnancy in the uterus, but a mass in the fallopian tube. The embryo has implanted outside the main cavity of the uterus. Most likely diagnosis?",
      a: "Ectopic pregnancy",
      e: "“Ecto” means outside. The baby started growing outside the womb.",
      m: "Ecto = outside." }
  ],
  et: [
    { cat: "Physics", q: "A swimmer swims 150 m in a 50 m pool (there, back, there). Displacement and distance?", a: "Displacement 50 m, distance 150 m",
      m: "Count the laps. Even laps = back home = displacement 0. Odd laps = at the other end." },
    { cat: "Astronomy", q: "Where in its orbit does Earth move slowest? And where is the Moon closest to Earth?", a: "Aphelion (slowest); perigee (Moon closest)",
      m: "Peri = near, Ap = away. Helion = Sun, Gee = Earth (geo)." },
    { cat: "Geometry", q: "A triangular prism has a right-triangle base with legs 6 cm and 8 cm, and height 5 cm. Volume?", a: "120 cm³",
      e: "Triangle floor = 6 × 8 ÷ 2 = 24. Then 24 × 5 = 120.", m: "Half, then times height." },
    { cat: "Chemistry", q: "Heat flows from which object to which? What tool shows two objects are at the same temperature?", a: "Hotter to colder; thermometer",
      m: "Cold spoon in hot soup: heat moves until both feel the same." },
    { cat: "Ratio", q: "Three numbers in the ratio 1:2:3 have a product of 48. Largest?", a: "6",
      e: "1 × 2 × 3 = 6. 48 ÷ 6 = 8 = 2 × 2 × 2. So times 2: 2, 4, 6." },
    { cat: "Ratio", q: "A cone and a cylinder have the same base and the same volume. Ratio of cone height to cylinder height?", a: "3:1",
      m: "Pointy shapes (cone, pyramid) hold only 1/3, so they must be 3 times taller." },
    { cat: "Biology", q: "Which blood vessels have valves? Which are the tiniest, where oxygen passes to cells?", a: "Veins; capillaries",
      m: "Arteries = Away. Veins = Valves. Capillaries = tiny, like hair." },
    { cat: "Fractions", q: "Mia had 3 1/3 pizzas. She gave away 1/2 and 3/4. How much is left?", a: "25/12 or 2 1/12",
      e: "Cut all pizzas into 12 slices: 40 − 6 − 9 = 25 slices." },
    { cat: "Physics", q: "Top of a wave? Bottom of a wave? Height from the middle line?", a: "Crest; trough; amplitude",
      m: "Crest = crown (top). Trough = low, like a feeding trough." },
    { cat: "Geometry", q: "Same painted 4 × 4 × 4 cube: how many small cubes have NO paint? How many have exactly 2 painted sides?", a: "No paint: 8; two sides: 24",
      e: "The unpainted inside is a 2 × 2 × 2 cube = 8. Two sides = middle of each edge: 12 edges × 2 = 24." }
  ],
  at: [
    { cat: "Ratio", q: "Divine's allowance rose 20% and Faith's fell 20%. Now equal. Ratio of the originals?", a: "2:3",
      e: "Test: ₱200 + 40 = ₱240 and ₱300 − 60 = ₱240.", m: "The one who got the raise started smaller." },
    { cat: "Chemistry", q: "TRUE or FALSE: water boils at 100 °C even on top of a high mountain.", a: "FALSE (it boils at a lower temperature up high)",
      m: "Less air pushing down = water boils more easily." },
    { cat: "Physics", q: "Same wave speed, but the frequency is cut in half. What happens to the wavelength?", a: "It doubles",
      m: "Jump rope: shake slower = fewer, longer waves." },
    { cat: "Equations", q: "10 questions: +4 for each correct, −1 for each wrong. Score is 25. How many correct?", a: "7",
      e: "Try 7: 7 × 4 = 28, minus 3 wrong = 25.", m: "Start guessing from the middle." },
    { cat: "Numbers", q: "Four consecutive even numbers; the largest is twice the smallest. Second largest?", a: "10",
      e: "When the largest is double, the smallest equals the gap. Gap for 4 evens = 6, so 6, 8, 10, 12." },
    { cat: "Earth science", q: "Which feels a higher intensity: a town near the epicenter or a town far away?", a: "Near the epicenter",
      m: "Speaker rule: louder up close. Magnitude stays the same everywhere." },
    { cat: "Biology", q: "The pulse on the neck is at which artery? What is the biggest artery in the body?", a: "Carotid artery; aorta",
      m: "Brachial = arm, radial = wrist, carotid = neck, femoral = thigh, aorta = biggest." },
    { cat: "LCM", q: "Buses leave every 12 and 18 minutes. Both leave at 6:00 AM. When do they leave together again?", a: "6:36 AM",
      m: "Together again = LCM (36). A few minutes later is still AM." },
    { cat: "Prime numbers", q: "The product of three primes plus 1 is 31. Sum of the primes?", a: "10",
      e: "31 − 1 = 30 = 2 × 3 × 5. 2 + 3 + 5 = 10.", m: "Test primes in order: 2, 3, 5, 7, 11, 13." },
    { cat: "Graphs", q: "A graph shows students who study more get higher scores. Which statement is supported?", a: "Studying more is linked to higher scores",
      m: "Only say what the graph shows. A graph shows a link, not proof of cause." }
  ],
  dt: [
    { cat: "Earth science", q: "What are the hottest months, March to May, called? What wind brings the rainy season?", a: "Hot dry season (summer); habagat",
      m: "Amihan = lamig (cold). Habagat = basa (wet)." },
    { cat: "Astronomy", q: "What did ancient Filipinos call Orion's belt? And the Pleiades are in which constellation?", a: "Balatik (Tres Marias); Taurus",
      m: "Moroporo = small cluster of 7. Balatik = 3 stars in a row." },
    { cat: "Discounts", q: "10 people, 2 are seniors with 20% off. The bill is ₱2,880. How much did each senior pay?", a: "₱240",
      e: "A senior counts as 0.8 of a person: 8 + 1.6 = 9.6. 2,880 ÷ 9.6 = 300. Senior pays 300 − 60 = 240." },
    { cat: "Chemistry", q: "Bacteria turn milk into yogurt. What process? What gas makes bread rise?", a: "Fermentation; carbon dioxide",
      m: "Tiny living things “eat” sugar and give off gas and new flavors." },
    { cat: "Percentage", q: "30 L of 10% salt water. How much water must be added to make it 6%?", a: "20 L",
      e: "Salt = 3 L and stays the same. 6% of 50 = 3, so total 50 L. Add 50 − 30 = 20 L." },
    { cat: "Biology", q: "Cassava and malunggay are grown from stem cuttings. What kind of reproduction?", a: "Vegetative (asexual) reproduction",
      m: "No seeds → plant parts → exact copies." },
    { cat: "Motion", q: "Anna walks 50 m/min, Ben 70 m/min, toward each other. They meet 30 m from the midpoint. How far apart were they?", a: "360 m",
      e: "Faster one walks 2 × 30 = 60 m extra. He gains 20 m each minute → 3 minutes. Together 120 m each minute × 3 = 360 m." },
    { cat: "Waves & light", q: "A spoon in water looks bent. What wave behavior of light is this?", a: "Refraction",
      m: "Reflect = return (echo). Refract = bend." },
    { cat: "Counting", q: "Sum of all 3-digit numbers using 1, 3, and 5 once each?", a: "1,998",
      e: "3 digits: (sum of digits) × 2 × 111. 9 × 2 × 111 = 1,998." },
    { cat: "Biology", q: "Sharp pain in the lower right belly because the appendix is swollen. Diagnosis?", a: "Appendicitis",
      m: "“-itis” means swollen or inflamed: tonsillitis, appendicitis." }
  ],
  ep: [
    { cat: "Physics", q: "A jeepney drives a 2 km loop and returns to the terminal. Distance and displacement?", a: "Distance 2 km, displacement 0",
      e: "It traveled 2 km, but it ended where it started, so it is 0 km from the start." },
    { cat: "Astronomy", q: "The point in the Moon's orbit where it is closest to Earth.", a: "Perigee",
      m: "Peri = near. Gee sounds like geo = Earth." },
    { cat: "Geometry", q: "A box has a 5 cm × 4 cm base and a volume of 100 cm³. Height?", a: "5 cm",
      e: "Floor of the box: 5 × 4 = 20. 20 × what = 100? Answer: 5." },
    { cat: "Physics", q: "Heat always flows from a ___ object to a ___ object.", a: "Hotter to colder",
      e: "Hot things give heat to cold things. That is why hot coffee cools down." },
    { cat: "Ratio", q: "Two numbers are in the ratio 3:4 and add to 35. Larger number?", a: "20",
      e: "3 parts + 4 parts = 7 parts = 35. One part = 5. Larger = 4 parts = 20." },
    { cat: "Geometry", q: "A cone and a cylinder have the same base and height. How many full cones fill the cylinder?", a: "3",
      m: "3 cones fill 1 can." },
    { cat: "Biology", q: "Which blood vessels have valves to stop blood flowing backward?", a: "Veins",
      m: "Veins = Valves." },
    { cat: "Fractions", q: "3 1/4 − 1 2/3", a: "1 7/12 (or 19/12)",
      e: "Cut into 12 slices: 3 1/4 = 39 slices and 1 2/3 = 20 slices. 39 − 20 = 19 slices = 1 whole and 7 slices." },
    { cat: "Physics", q: "The height of a wave from its rest position.", a: "Amplitude",
      e: "Amplitude = how tall the wave is from the middle line." },
    { cat: "Geometry", q: "A painted 3 × 3 × 3 cube is cut into unit cubes. How many have exactly 2 painted faces?", a: "12",
      e: "These are the middle pieces on each edge. A box has 12 edges, and each edge has 1 middle piece." }
  ],
  ap: [
    { cat: "Ratio", q: "Ana's savings rose 20%; Ben's fell 20%. Now equal. Ratio of Ana's original to Ben's original?", a: "2:3",
      e: "Ana ₱200 + ₱40 = ₱240. Ben ₱300 − ₱60 = ₱240. So 200 : 300 = 2 : 3." },
    { cat: "Physics", q: "TRUE or FALSE: sound travels faster in water than in air.", a: "TRUE",
      e: "Sound is about 4 times faster in water. That is why whales can hear each other from far away." },
    { cat: "Physics", q: "A sound wave moves at 340 m/s with a frequency of 170 Hz. Wavelength?", a: "2 m",
      e: "Wavelength = speed ÷ frequency. 340 ÷ 170 = 2." },
    { cat: "Equations", q: "A 10-item quiz: +5 per correct, −2 per wrong, all answered. Score is 29. How many correct?", a: "7",
      e: "Try 7 right: 7 × 5 = 35. 3 wrong: 3 × 2 = 6 lost. 35 − 6 = 29." },
    { cat: "Numbers", q: "Five consecutive odd numbers add to 75. Largest?", a: "19",
      e: "The middle number = 75 ÷ 5 = 15. Count up by 2: 15, 17, 19." },
    { cat: "Earth science", q: "The point on Earth's surface directly above where an earthquake starts.", a: "Epicenter",
      e: "Epicenter = the spot on the ground right above where the quake began underground." },
    { cat: "Biology", q: "The pulse is usually felt at the wrist on which artery?", a: "Radial artery",
      e: "Put 2 fingers on your wrist and feel the beat. That is the radial artery." },
    { cat: "LCM", q: "Bells ring every 8, 12, and 18 minutes. They ring together at 7:00 AM. When together again?", a: "8:12 AM",
      e: "LCM = 72 minutes = 1 hour 12 minutes. 7:00 + 1:12 = 8:12 AM." },
    { cat: "Prime numbers", q: "Two primes multiply to 221. Their sum?", a: "30",
      e: "Try dividing by primes: 221 ÷ 13 = 17. So 13 + 17 = 30." },
    { cat: "Graphs", q: "Children who sleep more get higher scores. Safest conclusion?",
      c: ["Sleep causes high scores", "More sleep is linked to higher scores", "High scores cause sleep", "All children must sleep 12 hours"],
      a: "B · More sleep is linked to higher scores",
      e: "The data only shows the two go together. It does not prove one causes the other." }
  ],
  dp: [
    { cat: "Earth science", q: "Warm, wet wind from the southwest that brings heavy rain from June to October.", a: "Habagat (southwest monsoon)",
      m: "Habagat = rainy wind. Amihan = cold wind." },
    { cat: "Astronomy", q: "Ancient Filipinos called Orion's belt this and used it to signal planting. Also called Tres Marias.", a: "Balatik",
      m: "Balatik = 3 stars in a row = Tres Marias." },
    { cat: "Discounts", q: "10 people eat out; 3 are seniors with 20% off. The bill is ₱3,290. How much did each senior pay?", a: "₱280",
      e: "3 seniors = 2.4 meals. Total = 7 + 2.4 = 9.4 meals. One meal = 3,290 ÷ 9.4 = ₱350. Senior pays 350 − 70 = ₱280." },
    { cat: "Chemistry", q: "An iron nail left in the rain turns reddish-brown. Name this chemical change.", a: "Rusting (oxidation or corrosion)",
      m: "Iron + water + air = rust." },
    { cat: "Percentage", q: "You have 10 L of 20% juice concentrate. How much water makes it 8%?", a: "15 L",
      e: "Pure juice: 20% of 10 L = 2 L. 8% of what = 2? 8% of 25 = 2. Total must be 25 L. 25 − 10 = add 15 L." },
    { cat: "Biology", q: "Scientists grow thousands of identical plants from tiny pieces of plant tissue in bottles. Method?", a: "Tissue culture",
      e: "Tiny plant pieces grow in bottles into many copies of the same plant." },
    { cat: "Motion", q: "Two cyclists start 180 km apart and ride toward each other at 40 and 50 km/h. How far from the midpoint do they meet?", a: "10 km",
      e: "Together they ride 90 km each hour. 180 ÷ 90 = 2 hours. Slower rider goes 80 km. The middle is at 90 km. 90 − 80 = 10 km." },
    { cat: "Waves & light", q: "A pencil in a glass of water looks broken. What wave behavior of light causes this?", a: "Refraction",
      e: "Light bends when it goes from water to air. Bending = refraction." },
    { cat: "Counting", q: "Sum of all 3-digit numbers using 2, 5, and 8 once each.", a: "3,330",
      e: "There are 6 numbers. Each digit sits in each place 2 times. 2 + 5 + 8 = 15. 15 × 2 = 30. 30 × 111 = 3,330." },
    { cat: "Biology", q: "A person's blood sugar stays too high because the pancreas makes too little insulin. Condition?", a: "Diabetes (diabetes mellitus)",
      e: "Insulin is like a key that lets sugar into the body's cells. Without enough keys, sugar stays in the blood." }
  ],
  mem: [
    { cat: "Motion", q: "Distance vs. displacement", a: "Distance = how far you walked in total. Displacement = how far you ended up from the start.", m: "Go and come back = displacement 0." },
    { cat: "Orbits", q: "Perihelion, aphelion, perigee, apogee", a: "Perihelion = nearest the Sun (fastest). Aphelion = farthest from the Sun (slowest). Perigee = nearest Earth. Apogee = farthest from Earth.", m: "Peri = near. Ap = away." },
    { cat: "Waves", q: "Parts of a wave", a: "Crest = top. Trough = bottom. Amplitude = how tall. Wavelength = top to next top." },
    { cat: "Waves", q: "Faster waves (higher frequency) → wavelength?", a: "More waves each second = each wave gets shorter.", m: "Shake a jump rope faster." },
    { cat: "Waves", q: "Reflection vs. refraction", a: "Reflection = bounces back (echo, mirror). Refraction = bends (pencil looks broken in water).", m: "Reflect = return. Refract = bend." },
    { cat: "Heat", q: "Which way does heat move?", a: "From hot to cold, until both are the same warmth.", m: "Cold spoon in hot soup." },
    { cat: "Body", q: "Arteries, veins, capillaries", a: "Arteries carry blood away from the heart and have thick walls. Veins bring blood back, have thin walls and valves. Capillaries are the tiniest.", m: "A for Artery, A for Away." },
    { cat: "Body", q: "Blood pressure and pulse: which arteries?", a: "Blood pressure cuff goes on the upper arm (brachial artery). Pulse at the wrist is the radial artery." },
    { cat: "Earthquakes", q: "Magnitude, intensity, epicenter", a: "Magnitude = how strong at the start (one number). Intensity = how strong it feels where you are. Epicenter = spot on the ground above the start.", m: "Like a speaker: louder up close." },
    { cat: "Seasons", q: "Philippine seasons and winds", a: "Rainy: June to November (habagat). Dry: December to May. Cool dry: December to February (amihan). Hot dry: March to May.", m: "Amihan = chilly. Habagat = heavy rain." },
    { cat: "Stars", q: "Filipino star names", a: "Moroporo = Pleiades (Seven Sisters). Balatik = 3 stars in a row (Tres Marias, Orion's belt)." },
    { cat: "Chemistry", q: "Fermentation", a: "Yeast eats sugar and makes gas bubbles (carbon dioxide). Bread puffs up." },
    { cat: "Plants", q: "Copying plants", a: "Plants grown from parts (banana suckers, cuttings, tissue culture) are exact copies. This is vegetative (asexual) reproduction." },
    { cat: "Volume", q: "Box vs. pyramid volume", a: "Box or can = floor × height. Pyramid or cone = only 1/3 of that.", m: "3 cones fill 1 can." },
    { cat: "Painted cube", q: "Painted cube pieces", a: "Corners have 3 painted sides (always 8). Edge-middles have 2. Face-middles have 1. The hidden center has 0.", m: "Corners = always 8." },
    { cat: "Percent", q: "Percent up and down", a: "Add 25% = original + one quarter. Take away 25% = original − one quarter.", m: "Try easy numbers like 100." },
    { cat: "Mixtures", q: "Adding water to a solution", a: "Adding water does not change how much pure juice or acid there is.", m: "Find the pure part first." },
    { cat: "LCM", q: "“Together again” problems", a: "Find the smallest number all the times go into (LCM).", m: "Lights, bells, buses." },
    { cat: "Strategy", q: "“How many correct?” problems", a: "Guess a number, check it, then adjust.", m: "Fast and safe." },
    { cat: "Counting", q: "Sum of all numbers made from different digits", a: "Sum of digits × times each digit sits in one place × 11…1.", m: "4 digits: × 6 × 1,111. 3 digits: × 2 × 111." },
    { cat: "Word parts", q: "peri, ap, ecto, -itis, geo, helio", a: "peri = near, ap = away, ecto = outside, -itis = swollen, geo = Earth, helio = Sun." }
  ],
  ml1: [
    { q: "GCF of 36 and 48", a: "12" }, { q: "LCM of 6, 8, and 12", a: "24" }, { q: "3/4 + 5/6", a: "1 7/12 (or 19/12)" },
    { q: "Write 0.25 as a fraction in lowest terms", a: "1/4" }, { q: "15% of 240", a: "36" }, { q: "2³ × 3²", a: "72" },
    { q: "12 + 6 ÷ 3 × 2 − 4", a: "12", e: "6 ÷ 3 = 2, × 2 = 4. 12 + 4 − 4 = 12." }, { q: "MMXXVI in Hindu-Arabic numerals", a: "2026" },
    { q: "Prime numbers between 20 and 30", a: "23 and 29" }, { q: "−7 + 12", a: "5" }, { q: "Write 3/5 as a percent", a: "60%" },
    { q: "4.5 × 100", a: "450" }, { q: "Round 3.14159 to the nearest hundredth", a: "3.14" }, { q: "Square root of 144", a: "12" },
    { q: "1 meter = how many centimeters?", a: "100 cm" }, { q: "Reciprocal of 2/3", a: "3/2" },
    { q: "A triangle with three equal sides", a: "Equilateral triangle" }, { q: "Perimeter of a square with 9 cm sides", a: "36 cm" },
    { q: "Place value of 7 in 4.078", a: "Hundredths" }, { q: "(−3) × (−4)", a: "12" }, { q: "Degrees in a right angle", a: "90°" },
    { q: "Minutes in 2.5 hours", a: "150 minutes" }
  ],
  ml2: [
    { q: "Area of a circle with radius 7 cm", a: "154 cm²", e: "22/7 × 7 × 7 = 154." },
    { q: "Circumference of a circle with diameter 14 cm", a: "44 cm", e: "22/7 × 14 = 44." },
    { q: "Volume of a box 5 cm × 4 cm × 3 cm", a: "60 cm³" },
    { q: "Boys to girls is 3:5 in a class of 40. How many girls?", a: "25", e: "8 parts = 40, 1 part = 5, girls = 5 parts = 25." },
    { q: "A car goes 60 km/h for 2.5 hours. How far?", a: "150 km" },
    { q: "Mean of 85, 90, 78, 92, 80", a: "85", e: "Total 425 ÷ 5 = 85." },
    { q: "₱800 item at 25% off. Sale price?", a: "₱600" },
    { q: "Probability of rolling an even number on one die", a: "1/2" },
    { q: "Next number: 2, 6, 12, 20, 30, ___", a: "42", e: "Gaps grow by 2: +4, +6, +8, +10, +12." },
    { q: "Solve 3x + 7 = 25", a: "x = 6" },
    { q: "Two angles of a triangle are 45° and 65°. Third angle?", a: "70°" },
    { q: "Median of 3, 9, 4, 7, 12, 5", a: "6", e: "In order: 3, 4, 5, 7, 9, 12. Middle two are 5 and 7 → 6." },
    { q: "Area of a triangle with base 10 cm and height 6 cm", a: "30 cm²" },
    { q: "2/3 of 3/4 of 48", a: "24" },
    { q: "Area of a parallelogram, base 8 cm, height 5 cm", a: "40 cm²" },
    { q: "Write 7/8 as a decimal", a: "0.875" },
    { q: "1.2 kg of rice costs ₱60. Price per kilogram?", a: "₱50" },
    { q: "Mode of 2, 3, 3, 5, 7, 3, 5", a: "3" },
    { q: "Find 2a + 3b when a = 4 and b = 5", a: "23" },
    { q: "Sum of the interior angles of a quadrilateral", a: "360°" }
  ],
  ml3: [
    { q: "1 + 2 + 3 + … + 50", a: "1,275", e: "n × (n + 1) ÷ 2 = 50 × 51 ÷ 2." },
    { q: "Number of diagonals in a hexagon", a: "9", e: "n × (n − 3) ÷ 2 = 6 × 3 ÷ 2." },
    { q: "A finishes a job in 6 days, B in 3 days. How long working together?", a: "2 days", e: "1/6 + 1/3 = 1/2 of the job per day." },
    { q: "Simple interest on ₱5,000 at 6% a year for 3 years", a: "₱900" },
    { q: "A cube has volume 125 cm³. Its surface area?", a: "150 cm²", e: "Side = 5. 6 faces × 25 = 150." },
    { q: "Ana is 3 times Ben's age. In 5 years their ages total 42. Ages now?", a: "Ben 8, Ana 24" },
    { q: "Last digit of 7¹⁰⁰", a: "1", e: "Last digits repeat 7, 9, 3, 1. 100 ÷ 4 has no remainder → 1." },
    { q: "Angle between the clock hands at 3:30", a: "75°" },
    { q: "A farm has 20 heads and 56 legs of chickens and pigs. How many pigs?", a: "8 pigs (12 chickens)" },
    { q: "A price rises 20%, then falls 20%. Net change?", a: "4% decrease", e: "100 → 120 → 96." },
    { q: "How many 3-digit numbers use 1, 2, 3, 4 with no repeated digit?", a: "24", e: "4 × 3 × 2." },
    { q: "Volume of a cylinder, radius 7 cm, height 10 cm", a: "1,540 cm³" },
    { q: "Five numbers average 20. One is removed; the other four average 18. Removed number?", a: "28", e: "100 − 72 = 28." },
    { q: "Three consecutive even numbers add to 78. What are they?", a: "24, 26, 28" },
    { q: "Ten people each shake hands once with everyone. How many handshakes?", a: "45", e: "10 × 9 ÷ 2." },
    { q: "Smallest number that leaves remainder 1 when divided by 2, 3, 4, 5, or 6", a: "61", e: "LCM is 60, plus 1." }
  ],
  mcl: [
    { q: "Total number of squares of all sizes on an 8 × 8 chessboard", a: "204", e: "1² + 2² + … + 8² = 204." },
    { q: "1/2 + 1/6 + 1/12 + 1/20 + 1/30", a: "5/6", e: "Each is 1/n − 1/(n+1), so it collapses to 1 − 1/6." },
    { q: "Number of zeros at the end of 25! (25 factorial)", a: "6", e: "Count the 5s: 25 ÷ 5 = 5, plus one more from 25 = 6." },
    { q: "A 200 m train passes a pole in 10 seconds. Speed in km/h?", a: "72 km/h", e: "20 m/s × 3.6 = 72." },
    { q: "Sum of the digits of 10¹⁰ − 1", a: "90", e: "It is 9,999,999,999: ten nines." }
  ],
  frm: [
    { q: "Area of a rectangle", a: "length × width" }, { q: "Area of a triangle", a: "base × height ÷ 2" },
    { q: "Area of a circle", a: "π × r × r" }, { q: "Circumference of a circle", a: "π × diameter" },
    { q: "Volume of a box", a: "length × width × height" }, { q: "Volume of a cylinder", a: "π × r × r × height" },
    { q: "Speed", a: "distance ÷ time" }, { q: "Percent of a number", a: "percent ÷ 100 × number" },
    { q: "Sum of 1 to n", a: "n × (n + 1) ÷ 2" }, { q: "Angles of a triangle add to…", a: "180°" },
    { q: "Angles of a quadrilateral add to…", a: "360°" },
    { q: "Order of operations", a: "Parentheses, Exponents, × and ÷ left to right, + and − left to right" },
    { q: "Unit changes: km, m, kg, L", a: "1 km = 1,000 m; 1 m = 100 cm; 1 kg = 1,000 g; 1 L = 1,000 mL" },
    { q: "Planets in order from the Sun", a: "Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus, Neptune" }
  ],
  sl1: [
    { q: "Largest organ of the human body", a: "Skin" }, { q: "Planet closest to the Sun", a: "Mercury" },
    { q: "Liquid changing to gas", a: "Evaporation" }, { q: "Chemical formula of water", a: "H₂O" },
    { q: "Organ that pumps blood", a: "Heart" }, { q: "Smallest unit of life", a: "Cell" },
    { q: "Animals without a backbone", a: "Invertebrates" }, { q: "Force that pulls objects toward Earth", a: "Gravity" },
    { q: "Gas plants take in to make food", a: "Carbon dioxide" }, { q: "Hottest planet", a: "Venus" },
    { q: "Largest planet", a: "Jupiter" }, { q: "Earth's natural satellite", a: "Moon" },
    { q: "Solid changing to liquid", a: "Melting" }, { q: "Main organs for breathing", a: "Lungs" },
    { q: "Organ that controls the whole body", a: "Brain" }, { q: "Instrument that measures temperature", a: "Thermometer" },
    { q: "Star at the center of the solar system", a: "Sun" }, { q: "Animals that eat only plants", a: "Herbivores" },
    { q: "Gas humans need to breathe in", a: "Oxygen" }, { q: "Body system made of bones", a: "Skeletal system" },
    { q: "Number of planets in the solar system", a: "8" }, { q: "Water vapor changing to liquid", a: "Condensation" }
  ],
  sl2: [
    { q: "How to get salt back from saltwater", a: "Evaporation" }, { q: "How to separate iron filings from sand", a: "Use a magnet" },
    { q: "Blood vessels that carry blood away from the heart", a: "Arteries" },
    { q: "Tiny air sacs in the lungs where gases are exchanged", a: "Alveoli" },
    { q: "Basic unit of the nervous system", a: "Neuron (nerve cell)" }, { q: "Instrument that records earthquakes", a: "Seismograph" },
    { q: "Scale PHIVOLCS uses for earthquake intensity (I to X)", a: "PHIVOLCS Earthquake Intensity Scale (PEIS)" },
    { q: "Most active volcano in the Philippines", a: "Mayon Volcano" },
    { q: "A wheelbarrow is which class of lever?", a: "Second class (load in the middle)" },
    { q: "Energy stored in food and batteries", a: "Chemical energy" }, { q: "Coastal forest of salt-tolerant trees", a: "Mangrove forest" },
    { q: "Mixture that looks the same throughout, like salt dissolved in water", a: "Solution (homogeneous mixture)" },
    { q: "How to separate sand from water", a: "Filtration (decantation also accepted)" },
    { q: "Organ where most digestion and absorption happen", a: "Small intestine" },
    { q: "Organs that filter blood and make urine", a: "Kidneys" },
    { q: "Invertebrates with jointed legs and a hard outer covering", a: "Arthropods" },
    { q: "Cold-blooded vertebrates with moist skin that live on land and in water", a: "Amphibians" },
    { q: "Force that slows motion between two surfaces", a: "Friction" }, { q: "Unit of force", a: "Newton (N)" },
    { q: "Eclipse when the Moon passes between the Sun and Earth", a: "Solar eclipse" },
    { q: "Outermost layer of the Earth, where we live", a: "Crust" }, { q: "Rock formed when magma or lava cools", a: "Igneous rock" }
  ],
  sl3: [
    { q: "Layer of the atmosphere where weather happens", a: "Troposphere" },
    { q: "Why is the sky blue?", a: "Air scatters blue light more than other colors" },
    { q: "Part of the blood that helps it clot", a: "Platelets" }, { q: "Approximate speed of light", a: "300,000 km per second" },
    { q: "In a series circuit, one bulb is removed. What happens?", a: "All the other bulbs go out" },
    { q: "Deep ocean trench off eastern Mindanao, near Caraga", a: "Philippine Trench" },
    { q: "Products of photosynthesis", a: "Glucose (sugar) and oxygen" }, { q: "Male part of a flower", a: "Stamen (the anther makes pollen)" },
    { q: "Days from one new moon to the next", a: "About 29.5 days" },
    { q: "Green pigment in plants that captures sunlight", a: "Chlorophyll" },
    { q: "Number of chambers in the human heart", a: "4" }, { q: "Longest bone in the human body", a: "Femur (thigh bone)" },
    { q: "Smallest bone in the human body", a: "Stapes (stirrup), in the ear" },
    { q: "Simple machine that is a sloping ramp", a: "Inclined plane" },
    { q: "Relationship where both organisms benefit", a: "Mutualism" },
    { q: "Belt of volcanoes and earthquakes around the Pacific that includes the Philippines", a: "Pacific Ring of Fire" },
    { q: "Breaking down of rocks into smaller pieces", a: "Weathering" },
    { q: "Energy from heat inside the Earth, used widely in the Philippines", a: "Geothermal energy" },
    { q: "Blood cells that carry oxygen", a: "Red blood cells" }
  ],
  scl: [
    { q: "Group of stars forming a pattern in the sky", a: "Constellation" },
    { q: "Metal that is liquid at room temperature", a: "Mercury" },
    { q: "Boiling point of water at sea level", a: "100 °C" }, { q: "Part of the cell that controls its activities", a: "Nucleus" },
    { q: "Highest tropical cyclone wind signal used by PAGASA", a: "Signal No. 5" },
    { q: "Scientist who stated the three laws of motion", a: "Isaac Newton" },
    { q: "Government agency that issues weather forecasts", a: "PAGASA" }
  ],
  tch: [
    { q: "What does DOST stand for?", a: "Department of Science and Technology" },
    { q: "What does PSHS stand for?", a: "Philippine Science High School" },
    { q: "What does NSTW stand for?", a: "National Science and Technology Week" },
    { q: "The “brain” of the computer", a: "CPU (Central Processing Unit)" }, { q: "1 byte = how many bits?", a: "8" },
    { q: "What does RAM stand for?", a: "Random Access Memory" }, { q: "What does WWW stand for?", a: "World Wide Web" },
    { q: "Input device used for typing", a: "Keyboard" }, { q: "Output device that shows pictures and text", a: "Monitor" },
    { q: "Inventor of the telephone", a: "Alexander Graham Bell" }, { q: "Inventor of the practical light bulb", a: "Thomas Edison" },
    { q: "Filipino National Scientist in pediatrics who improved the baby incubator", a: "Dr. Fe del Mundo" },
    { q: "Filipino inventor linked to the two-way videophone", a: "Gregorio Y. Zara" },
    { q: "Filipino engineer known for computer chip and graphics technology", a: "Diosdado Banatao" },
    { q: "Filipino National Scientist known for marine sanctuaries such as Apo Island", a: "Dr. Angel Alcala" },
    { q: "Energy taken directly from sunlight", a: "Solar energy" },
    { q: "Energy from flowing water, like the Agus River plants in Mindanao", a: "Hydroelectric energy" },
    { q: "Turning waste into new materials", a: "Recycling" },
    { q: "Large protected wetland in Agusan del Sur", a: "Agusan Marsh" },
    { q: "Lake in Caraga often called the deepest in the Philippines", a: "Lake Mainit" },
    { q: "Main metal mined in Surigao and other Caraga provinces", a: "Nickel" },
    { q: "Philippine agency that monitors volcanoes and earthquakes", a: "PHIVOLCS" }
  ]
};
