// Extra data per card, keyed by "deckId:index" (index starts at 0 in cards.js).
//   h    = words to highlight (bold marker) in the question, explanation, and trick
//   k    = extra accepted typed answers. "a+b" means the answer must contain both a and b.
//   self = long answer: the player checks it himself instead of typing
//   c/a  = replace the choices/answer (turns a typed card into multiple choice)
window.KEYS = {
  "e25:0": { h: ["displacement", "distance", "there and back", "Go and come back"] },
  "e25:1": { h: ["fastest", "Perihelion", "nearest the Sun", "Peri = near"] },
  "e25:2": { h: ["legs 3 cm and 4 cm", "60 cm³", "half", "Half, then times height"] },
  "e25:3": { h: ["thermal equilibrium", "same temperature", "same warmth"] },
  "e25:4": { h: ["ratio 2:3:5", "product is 810", "Multiply each by 3"] },
  "e25:5": { h: ["equal base areas", "volumes are equal", "1/3", "3 times as tall", "Pointy shapes hold 1/3"] },
  "e25:6": { h: ["vein", "thick walls", "middle wall is thin", "A for Artery, A for Away"] },
  "e25:7": { h: ["2 1/2 pizzas", "3/4", "2/3", "12 slices", "13 slices"] },
  "e25:8": { h: ["exact same place", "next cycle", "Wavelength", "next wave top"] },
  "e25:9": { h: ["three sides painted", "corner pieces", "8 corners", "Corners = always 8"] },

  "a25:0": { h: ["increased by 25%", "decreased by 25%", "Equal!", "started smaller"] },
  "a25:1": { h: ["solid, liquid, and gas", "same time", "triple point"] },
  "a25:2": { h: ["frequency is doubled", "wavelength", "half as long", "Shake a jump rope faster"] },
  "a25:3": { h: ["gained 4 points", "lost 3 points", "Guess, check, adjust"] },
  "a25:4": { h: ["6 consecutive even numbers", "two times the smallest", "10 more"] },
  "a25:5": { h: ["magnitude", "intensity", "where it started", "how strong it feels where you are", "loud up close"] },
  "a25:6": { h: ["blood pressure", "upper arm", "brachial", "Brachial = arm"] },
  "a25:7": { h: ["12, 30, and 66 seconds", "LCM", "660 seconds = 11 minutes", "Watch AM and PM!"] },
  "a25:8": { h: ["added to 1", "1222", "1221", "3 + 11 + 37 = 51"] },
  "a25:9": { h: ["Only choose what the graph shows", "more sugar, more cavities"] },

  "d25:0": { h: ["amihan", "cooler temperatures", "dry season", "Habagat = rainy wind", "Amihan = lamig (cold)"], k: ["cool dry season"] },
  "d25:1": { h: ["Moroporo", "Pleiades", "Seven Sisters"], k: ["seven sisters", "pleiades cluster"] },
  "d25:2": { h: ["20% senior discount", "8/10 of a meal", "₱345", "0.8 of a person"] },
  "d25:3": { h: ["yeast", "carbon dioxide and alcohol", "gas bubbles"] },
  "d25:4": { h: ["12%", "15% acid", "Pure acid", "25 L", "never changes the pure part"] },
  "d25:5": { h: ["seedless", "genetically identical", "plant parts", "exact copies"], k: ["vegetative", "asexual reproduction", "vegetative propagation"] },
  "d25:6": { h: ["60 m/min", "90 m/min", "20 m from the midpoint", "gains 30 m", "2 × (distance from midpoint)"] },
  "d25:7": { h: ["echoes", "bouncing back", "Reflect = return"], k: ["sound reflection", "wave reflection"] },
  "d25:8": { h: ["digits 1, 3, 4, and 7", "6 times", "1,111", "4 digits: sum × 6 × 1,111"] },
  "d25:9": { h: ["fallopian tube", "outside", "Ecto = outside"], k: ["ectopic"] },

  "et:0": { h: ["150 m", "Odd laps"], k: ["50+150"] },
  "et:1": { h: ["slowest", "closest to Earth", "Peri = near, Ap = away"], k: ["aphelion+perigee"] },
  "et:2": { h: ["legs 6 cm and 8 cm", "height 5 cm", "Half, then times height"] },
  "et:3": { h: ["Heat flows", "same temperature", "thermometer"], k: ["hot+cold+thermometer"] },
  "et:4": { h: ["ratio 1:2:3", "product of 48", "times 2"] },
  "et:5": { h: ["same volume", "1/3", "3 times taller"] },
  "et:6": { h: ["valves", "tiniest", "Veins = Valves", "Capillaries = tiny"], k: ["vein+capillar"] },
  "et:7": { h: ["3 1/3 pizzas", "12 slices"] },
  "et:8": { h: ["Top", "Bottom", "Height from the middle line", "Crest = crown", "Trough = low"], k: ["crest+trough+amplitude"] },
  "et:9": { h: ["NO paint", "exactly 2 painted sides", "2 × 2 × 2", "12 edges × 2"], k: ["8+24"] },

  "at:0": { h: ["rose 20%", "fell 20%", "started smaller"] },
  "at:1": { h: ["100 °C", "high mountain", "Less air"] },
  "at:2": { h: ["cut in half", "fewer, longer waves"], k: ["double", "doubled", "it will double", "2 times longer"] },
  "at:3": { h: ["+4", "−1", "Score is 25", "middle"] },
  "at:4": { h: ["Four consecutive even numbers", "twice the smallest", "smallest equals the gap"] },
  "at:5": { h: ["higher intensity", "near the epicenter", "louder up close"], k: ["near", "the town near the epicenter", "near town"] },
  "at:6": { h: ["neck", "biggest artery", "carotid = neck", "aorta = biggest"], k: ["carotid+aorta"] },
  "at:7": { h: ["every 12 and 18 minutes", "LCM (36)", "still AM"] },
  "at:8": { h: ["plus 1 is 31", "2 × 3 × 5", "Test primes in order"] },
  "at:9": { h: ["study more", "higher scores", "a link, not proof"],
    c: ["Studying more causes higher scores for everyone", "Studying more is linked to higher scores", "Higher scores make students study more", "Students should never rest"],
    a: "B · Studying more is linked to higher scores" },

  "dt:0": { h: ["March to May", "rainy season", "Habagat = basa (wet)"], k: ["summer+habagat", "hot dry+habagat", "dry+habagat"] },
  "dt:1": { h: ["Orion's belt", "Pleiades", "Balatik = 3 stars in a row"], k: ["balatik+taurus"] },
  "dt:2": { h: ["2 are seniors", "20% off", "0.8 of a person"] },
  "dt:3": { h: ["milk into yogurt", "bread rise"], k: ["fermentation+carbon dioxide", "fermentation+co2"] },
  "dt:4": { h: ["10% salt water", "6%", "Salt = 3 L", "stays the same"] },
  "dt:5": { h: ["stem cuttings", "exact copies"], k: ["vegetative", "asexual reproduction", "vegetative propagation"] },
  "dt:6": { h: ["30 m from the midpoint", "2 × 30 = 60 m extra", "gains 20 m each minute"] },
  "dt:7": { h: ["looks bent", "Refract = bend"] },
  "dt:8": { h: ["1, 3, and 5", "× 2 × 111"] },
  "dt:9": { h: ["appendix is swollen", "-itis", "swollen or inflamed"] },

  "ep:0": { h: ["returns to the terminal", "ended where it started"], k: ["2+0"] },
  "ep:1": { h: ["closest to Earth", "Peri", "geo = Earth"] },
  "ep:2": { h: ["5 cm × 4 cm base", "volume 100 cm³"] },
  "ep:3": { h: ["Heat always flows", "Hot things give heat to cold things"], k: ["hot+cold"] },
  "ep:4": { h: ["ratio 3:4", "add to 35", "One part = 5"] },
  "ep:5": { h: ["same base and height", "3 cones fill 1 can"] },
  "ep:6": { h: ["valves", "flowing backward", "Veins = Valves"], k: ["vein"] },
  "ep:7": { h: ["12 slices", "39 − 20 = 19"] },
  "ep:8": { h: ["height of a wave", "rest position", "middle line"] },
  "ep:9": { h: ["exactly 2 painted faces", "middle pieces", "12 edges"] },

  "ap:0": { h: ["rose 20%", "fell 20%"] },
  "ap:1": { h: ["faster in water", "4 times faster"] },
  "ap:2": { h: ["340 m/s", "170 Hz", "speed ÷ frequency"] },
  "ap:3": { h: ["+5 per correct", "−2 per wrong", "Score is 29"] },
  "ap:4": { h: ["Five consecutive odd numbers", "middle number", "75 ÷ 5"] },
  "ap:5": { h: ["directly above", "Epicenter"], k: ["epicentre"] },
  "ap:6": { h: ["wrist", "radial artery"], k: ["radial"] },
  "ap:7": { h: ["every 8, 12, and 18 minutes", "LCM = 72 minutes"] },
  "ap:8": { h: ["multiply to 221", "221 ÷ 13 = 17"] },
  "ap:9": { h: ["sleep more", "go together", "does not prove"] },

  "dp:0": { h: ["southwest", "heavy rain", "June to October", "Habagat = rainy wind"], k: ["habagat", "southwest monsoon"] },
  "dp:1": { h: ["Orion's belt", "Tres Marias", "Balatik = 3 stars in a row"] },
  "dp:2": { h: ["3 are seniors", "20% off", "2.4 meals", "₱350"] },
  "dp:3": { h: ["iron nail", "reddish-brown", "Iron + water + air = rust"], k: ["rust", "oxidation", "corrosion"] },
  "dp:4": { h: ["20% juice", "8%", "Pure juice", "25 L"] },
  "dp:5": { h: ["tiny pieces of plant tissue", "in bottles"] },
  "dp:6": { h: ["180 km apart", "90 km each hour", "The middle is at 90 km"] },
  "dp:7": { h: ["looks broken", "Bending = refraction"] },
  "dp:8": { h: ["2, 5, and 8", "each place 2 times", "× 111"] },
  "dp:9": { h: ["blood sugar", "pancreas", "insulin", "key"], k: ["diabetes mellitus"] },

  "mem:0": { h: ["Distance", "Displacement", "displacement 0"], self: true },
  "mem:1": { h: ["Perihelion", "Aphelion", "Perigee", "Apogee", "Peri = near", "Ap = away"], self: true },
  "mem:2": { h: ["Crest", "Trough", "Amplitude", "Wavelength"], self: true },
  "mem:3": { h: ["shorter", "faster"], self: true },
  "mem:4": { h: ["Reflection", "Refraction", "bounces back", "bends", "Reflect = return", "Refract = bend"], self: true },
  "mem:5": { h: ["hot to cold", "same warmth"], self: true },
  "mem:6": { h: ["Arteries", "away", "Veins", "valves", "Capillaries"], self: true },
  "mem:7": { h: ["brachial artery", "radial artery", "upper arm", "wrist"], self: true },
  "mem:8": { h: ["Magnitude", "Intensity", "Epicenter", "louder up close"], self: true },
  "mem:9": { h: ["habagat", "amihan", "June to November", "December to February", "March to May"], self: true },
  "mem:10": { h: ["Moroporo", "Pleiades", "Balatik", "Tres Marias"], self: true },
  "mem:11": { h: ["Yeast", "gas bubbles", "carbon dioxide"], self: true },
  "mem:12": { h: ["exact copies", "vegetative (asexual) reproduction"], self: true },
  "mem:13": { h: ["floor × height", "1/3", "3 cones fill 1 can"], self: true },
  "mem:14": { h: ["Corners", "always 8", "Edge-middles", "Face-middles", "hidden center"], self: true },
  "mem:15": { h: ["one quarter", "easy numbers like 100"], self: true },
  "mem:16": { h: ["does not change", "pure part"], self: true },
  "mem:17": { h: ["LCM", "smallest number"], self: true },
  "mem:18": { h: ["Guess", "check", "adjust"], self: true },
  "mem:19": { h: ["× 6 × 1,111", "× 2 × 111"], self: true },
  "mem:20": { h: ["near", "away", "outside", "swollen", "Earth", "Sun"], self: true },

  // Warm-ups: extra accepted spellings and multi-part answers
  "ml1:2": { k: ["19/12"] },
  "ml1:8": { k: ["23+29"] },
  "ml1:15": { k: ["1 1/2", "1.5"] },
  "ml1:16": { k: ["equilateral"] },
  "ml2:7": { k: ["0.5", "50%", "3/6"] },
  "ml3:5": { k: ["8+24"] },
  "ml3:9": { k: ["4% decrease", "decrease 4%", "decreased by 4%", "4% less", "4% loss"] },
  "ml3:13": { k: ["24+26+28"] },
  "ml3:8": { k: ["8"] },
  "sl1:3": { k: ["h2o"] },
  "sl1:8": { k: ["co2"] },
  "sl2:1": { k: ["magnet", "magnetism"] },
  "sl2:6": { k: ["peis", "phivolcs earthquake intensity scale", "phivolcs scale"] },
  "sl2:8": { k: ["second class", "2nd class", "class 2", "second"] },
  "sl2:12": { k: ["filtration", "decantation", "filtering"] },
  "sl2:18": { k: ["newton", "newtons", "n"] },
  "sl3:1": { self: true },
  "sl3:3": { k: ["300000", "300000 km/s", "300000 km per second", "300000 kilometers per second"] },
  "sl3:4": { self: true },
  "sl3:6": { k: ["glucose+oxygen", "sugar+oxygen"] },
  "sl3:7": { k: ["stamen", "anther"] },
  "sl3:8": { k: ["29.5", "29.5 days", "29 1/2 days"] },
  "sl3:12": { k: ["stapes", "stirrup"] },
  "sl3:15": { k: ["ring of fire", "pacific ring of fire"] },
  "sl3:18": { k: ["rbc", "red blood cell", "erythrocytes"] },
  "scl:4": { k: ["5", "signal 5", "signal number 5", "signal no 5"] },
  "scl:5": { k: ["newton", "sir isaac newton"] },
  "tch:3": { k: ["cpu"] },
  "tch:9": { k: ["graham bell", "bell"] },
  "tch:10": { k: ["edison"] },
  "tch:11": { k: ["fe del mundo", "del mundo"] },
  "tch:12": { k: ["gregorio zara", "zara"] },
  "tch:13": { k: ["banatao"] },
  "tch:14": { k: ["angel alcala", "alcala"] },
  "tch:16": { k: ["hydroelectric", "hydropower", "hydro"] },
  "tch:19": { k: ["mainit"] }
};
// Every formula card is checked by the player.
(function () { for (var i = 0; i < 14; i++) window.KEYS["frm:" + i] = { self: true }; })();
