// Extra science questions written in the style of the 2025 DOST Caraga question committee:
// waves and sound, the human body, local news and places, Filipino knowledge,
// "you are the expert" scenarios, and data reading.
// Same fields as cards.js, plus h (highlight) and k (extra accepted answers).

(function () {
  var g = { id: "csci", name: "Committee picks: Science", note: "170 new science questions made like the 2025 ones. Scenarios, local news, the body, waves." };
  var at = window.GROUPS.findIndex(function (x) { return x.id === "p26"; });
  window.GROUPS.splice(at + 1, 0, g); // show right after the 2026-style practice
})();

window.DECKS.push(
  { id: "se", group: "csci", name: "Easy science", round: "easy", pts: 1, time: 15 },
  { id: "sa", group: "csci", name: "Average science", round: "average", pts: 2, time: 30 },
  { id: "sd", group: "csci", name: "Difficult science", round: "difficult", pts: 3, time: 60 },
  { id: "stf", group: "csci", name: "True or false blitz", round: "average", pts: 2, time: 20 },
  { id: "sph", group: "csci", name: "Caraga & PH science", round: "mix", pts: 2, time: 30 }
);

var TF = ["True", "False"];

window.CARDS.se = [
  { cat: "Motion", q: "A jeepney travels 60 km in 2 hours. What is its average speed?", a: "30 km/h",
    e: "Speed = distance ÷ time. 60 ÷ 2 = 30.", m: "Speed = distance ÷ time.", h: ["60 km", "2 hours", "average speed"] },
  { cat: "Motion", q: "Which of these is a vector quantity (it has a direction)?", c: ["Distance", "Speed", "Displacement", "Time"], a: "C · Displacement",
    e: "Displacement says how far AND which way. Distance and speed have no direction.", m: "Vector = has a direction arrow.", h: ["vector quantity", "direction"] },
  { cat: "Waves", q: "What is the unit of frequency?", a: "Hertz (Hz)", k: ["hz"], e: "1 hertz = 1 wave per second.", h: ["frequency"] },
  { cat: "Waves & sound", q: "Sound CANNOT travel through which of these?", c: ["Water", "Steel", "Air", "Vacuum (empty space)"], a: "D · Vacuum (empty space)",
    e: "Sound needs particles to shake. Empty space has none, so space is silent.", m: "No matter, no sound.", h: ["CANNOT"] },
  { cat: "Light", q: "Which color of visible light has the LONGEST wavelength?", c: ["Violet", "Green", "Red", "Blue"], a: "C · Red",
    e: "In ROYGBIV, red has the longest waves and violet the shortest.", m: "Red = Really long.", h: ["LONGEST wavelength"] },
  { cat: "Heat", q: "A metal spoon in hot soup gets hot all the way to the handle. What kind of heat transfer is this?", a: "Conduction",
    e: "Heat passes by touch, particle to particle.", m: "Conduction = Contact.", h: ["metal spoon", "handle"] },
  { cat: "Heat", q: "Warm air rises and cool air sinks, carrying heat around a room. What kind of heat transfer is this?", a: "Convection",
    e: "Heat is carried by moving liquids or gases.", m: "Convection = Circulating current.", h: ["rises", "sinks"] },
  { cat: "Heat", q: "Heat from the Sun reaches Earth through empty space. What kind of heat transfer is this?", a: "Radiation",
    e: "Radiation needs no matter. It travels as waves.", m: "Radiation = Rays.", h: ["empty space"] },
  { cat: "Electricity", q: "Which material is a good conductor of electricity?", c: ["Rubber", "Copper", "Plastic", "Wood"], a: "B · Copper",
    e: "Metals like copper let electricity flow. That is why wires are copper inside and plastic outside.", h: ["good conductor"] },
  { cat: "Force", q: "An object at rest stays at rest, and a moving object keeps moving, unless a force acts on it. What is this property called?", a: "Inertia",
    e: "This is Newton's First Law, the Law of Inertia. It is why you lurch forward when a jeepney stops suddenly.", h: ["stays at rest", "keeps moving"] },
  { cat: "Chemistry", q: "Which of these is a CHEMICAL change?", c: ["Melting ice", "Cutting paper", "Burning wood", "Dissolving sugar"], a: "C · Burning wood",
    e: "Burning makes new substances (ash, smoke, gases). The others only change shape or state.", m: "New substance = chemical change.", h: ["CHEMICAL"] },
  { cat: "Chemistry", q: "The smallest particle of an element that still has the properties of that element.", a: "Atom", h: ["smallest particle", "element"] },
  { cat: "Matter", q: "Which state of matter has a definite volume but NO definite shape?", c: ["Solid", "Liquid", "Gas", "Plasma"], a: "B · Liquid",
    e: "A liquid takes the shape of its container but keeps its volume.", h: ["definite volume", "NO definite shape"] },
  { cat: "Chemistry", q: "What is the pH of pure water?", a: "7 (neutral)", k: ["7", "neutral"],
    e: "Below 7 = acid, 7 = neutral, above 7 = base.", m: "7 is the middle.", h: ["pH", "pure water"] },
  { cat: "Chemistry", q: "Sour vinegar (suka) is a(n):", c: ["Acid", "Base", "Neutral substance", "Metal"], a: "A · Acid",
    e: "Acids taste sour. Vinegar has acetic acid.", m: "Sour = acid. Slippery and bitter = base.", h: ["Sour vinegar"] },
  { cat: "Cells", q: "Known as the “powerhouse of the cell” because it releases energy from food.", a: "Mitochondrion", k: ["mitochondria"], h: ["powerhouse of the cell"] },
  { cat: "Plants", q: "The process plants use to make food from sunlight, water, and carbon dioxide.", a: "Photosynthesis",
    e: "Photo = light, synthesis = putting together.", h: ["make food", "sunlight"] },
  { cat: "Human body", q: "Which blood cells fight infection?", c: ["Red blood cells", "White blood cells", "Platelets", "Plasma"], a: "B · White blood cells",
    e: "White blood cells are the body's soldiers.", m: "Red carries oxygen, White is the Warrior, Platelets Patch.", h: ["fight infection"] },
  { cat: "Human body", q: "The dome-shaped muscle below the lungs that helps us breathe.", a: "Diaphragm", h: ["below the lungs", "breathe"] },
  { cat: "Human body", q: "Where does digestion BEGIN?", c: ["Stomach", "Mouth", "Small intestine", "Esophagus"], a: "B · Mouth",
    e: "Teeth chew and saliva starts breaking down starch.", h: ["BEGIN"] },
  { cat: "Ecology", q: "Organisms like bacteria and fungi that break down dead plants and animals.", a: "Decomposers", k: ["decomposer"], h: ["break down dead"] },
  { cat: "Human body", q: "Which vitamin does your skin make when it gets sunlight?", c: ["Vitamin A", "Vitamin B", "Vitamin C", "Vitamin D"], a: "D · Vitamin D",
    e: "Vitamin D helps bones use calcium.", m: "D for Daylight.", h: ["skin", "sunlight"] },
  { cat: "Animals", q: "Animals like owls and bats that are active at night are called?", a: "Nocturnal", h: ["active at night"] },
  { cat: "Earth science", q: "Hot melted rock BENEATH Earth's surface.", a: "Magma", e: "Magma is underground. When it comes out, it is called lava.", m: "Magma = Middle (inside). Lava = Landed outside.", h: ["BENEATH"] },
  { cat: "Earth science", q: "The scale scientists use to compare the hardness of minerals, from talc (1) to diamond (10).", a: "Mohs scale", k: ["mohs", "mohs hardness scale"], h: ["hardness of minerals"] },
  { cat: "Earth science", q: "Which layer of Earth is the HOTTEST?", c: ["Crust", "Mantle", "Outer core", "Inner core"], a: "D · Inner core",
    e: "The deeper you go, the hotter it gets. The inner core is about as hot as the Sun's surface.", h: ["HOTTEST"] },
  { cat: "Earth science", q: "Giant sea waves caused by undersea earthquakes.", a: "Tsunami", h: ["undersea earthquakes"] },
  { cat: "Weather", q: "Instrument that measures air pressure.", a: "Barometer", m: "Baro = pressure.", h: ["air pressure"] },
  { cat: "Weather", q: "Instrument that measures wind speed.", a: "Anemometer", m: "Anemo = wind.", h: ["wind speed"] },
  { cat: "Space", q: "Which planet is called the Red Planet?", a: "Mars", e: "Its soil has lots of iron oxide (rust).", h: ["Red Planet"] },
  { cat: "Space", q: "What causes day and night?", c: ["Earth's revolution around the Sun", "Earth's rotation on its axis", "The Moon's orbit", "The Sun moving around Earth"], a: "B · Earth's rotation on its axis",
    e: "Earth spins once every 24 hours.", m: "Rotation = spin = day. Revolution = trip around the Sun = year.", h: ["day and night"] },
  { cat: "Space", q: "The Moon phase when its whole lit side faces Earth.", a: "Full moon", h: ["whole lit side"] },
  { cat: "Space", q: "The Sun is what kind of space object?", a: "A star", k: ["star"], h: ["Sun"] },
  { cat: "Space", q: "Which planet has the biggest, brightest rings?", c: ["Jupiter", "Saturn", "Uranus", "Neptune"], a: "B · Saturn", h: ["rings"] },
  { cat: "Energy", q: "The energy of a MOVING object.", a: "Kinetic energy", k: ["kinetic"], m: "Kinetic = Kicking, moving.", h: ["MOVING"] },
  { cat: "Energy", q: "Stored energy because of position, like a coconut high up on a tree.", a: "Potential energy", k: ["potential", "gravitational potential energy"], h: ["Stored energy", "position"] },
  { cat: "Simple machines", q: "A seesaw is an example of which simple machine?", a: "Lever", k: ["first class lever", "1st class lever"], h: ["seesaw"] },
  { cat: "Plants", q: "Which plant part absorbs water and minerals from the soil?", a: "Roots", k: ["root"], h: ["absorbs water"] },
  { cat: "Human body", q: "How many bones are in an adult human body?", a: "206", h: ["adult"] },
  { cat: "Matter", q: "Which of these is a MIXTURE?", c: ["Table salt", "Pure water", "Air", "Gold"], a: "C · Air",
    e: "Air is a mix of nitrogen, oxygen, carbon dioxide, and other gases.", h: ["MIXTURE"] }
];

window.CARDS.sa = [
  { cat: "Waves", q: "A wave has a frequency of 5 Hz and a wavelength of 2 m. What is its speed?", a: "10 m/s",
    e: "Speed = frequency × wavelength. 5 × 2 = 10.", m: "v = f × λ.", h: ["5 Hz", "2 m", "speed"] },
  { cat: "Waves", q: "Which wave NEEDS a medium (matter) to travel?", c: ["Light", "Radio waves", "Sound", "X-rays"], a: "C · Sound",
    e: "Light, radio, and X-rays are electromagnetic waves and can cross empty space. Sound cannot.", h: ["NEEDS a medium"] },
  { cat: "Sound", q: "The loudness of sound is measured in which unit?", a: "Decibels (dB)", k: ["decibel", "db"], h: ["loudness"] },
  { cat: "Sound", q: "A higher-pitched sound has a higher:", c: ["Amplitude", "Frequency", "Wavelength", "Speed"], a: "B · Frequency",
    e: "Pitch depends on frequency. Loudness depends on amplitude.", m: "Pitch = frequency. Loud = amplitude.", h: ["higher-pitched"] },
  { cat: "Light", q: "When light bounces off a flat mirror, the angle of incidence equals the angle of ___.", a: "Reflection",
    e: "This is the Law of Reflection.", h: ["bounces off", "angle of incidence"] },
  { cat: "Light", q: "A glass prism splits white light into a rainbow of colors. What is this called?", c: ["Reflection", "Dispersion", "Diffraction", "Absorption"], a: "B · Dispersion",
    e: "Each color bends a different amount, so they spread out. Rainbows form the same way in raindrops.", h: ["prism", "rainbow"] },
  { cat: "Motion", q: "A car speeds up from 0 to 20 m/s in 4 seconds. What is its acceleration?", a: "5 m/s²", k: ["5", "5 m/s2", "5 m/s/s"],
    e: "Acceleration = change in speed ÷ time = 20 ÷ 4 = 5.", h: ["0 to 20 m/s", "4 seconds", "acceleration"] },
  { cat: "Force", q: "A rocket lifts off by pushing hot gas DOWN, and the gas pushes the rocket UP. Which of Newton's laws explains this?", a: "Third law (action and reaction)",
    k: ["third", "3rd", "3rd law", "newton's third law", "law of action and reaction", "action and reaction", "third law"], m: "Every action has an equal and opposite reaction.", h: ["DOWN", "UP"] },
  { cat: "Force", q: "An astronaut has a mass of 50 kg on Earth. What is her mass on the Moon?", a: "50 kg",
    e: "Mass (amount of matter) does not change. Only weight changes: on the Moon she weighs about 1/6 as much.", m: "Mass stays. Weight changes.", h: ["mass", "on the Moon"] },
  { cat: "Electricity", q: "In a PARALLEL circuit, one bulb burns out. What happens to the other bulbs?", c: ["They all go out", "They stay lit", "They all get dimmer", "The battery explodes"], a: "B · They stay lit",
    e: "Each bulb has its own path. In a series circuit, all would go out.", m: "Parallel = separate paths. Series = one path.", h: ["PARALLEL"] },
  { cat: "Electricity", q: "What is the unit of electrical resistance?", a: "Ohm", k: ["ohms", "Ω"], h: ["resistance"] },
  { cat: "Energy", q: "A flashlight changes the chemical energy in its batteries mainly into what kind of energy?", a: "Light energy", k: ["light", "radiant", "radiant energy", "light and heat"], h: ["flashlight", "chemical energy"] },
  { cat: "Heat", q: "A metal spoon and a wooden spoon sit in the same room. Why does the metal one feel colder to touch?",
    c: ["Metal is colder", "Metal carries heat away from your hand faster", "Wood makes its own heat", "Metal has no heat"], a: "B · Metal carries heat away from your hand faster",
    e: "Both are the same temperature. Metal is a better conductor, so it pulls heat from your skin faster.", h: ["same room", "feel colder"] },
  { cat: "Chemistry", q: "Which is NOT a sign of a chemical change?", c: ["Gas bubbles form", "Color changes", "Shape changes", "A new smell"], a: "C · Shape changes",
    e: "Changing shape (like folding paper) makes no new substance. It is a physical change.", h: ["NOT"] },
  { cat: "Chemistry", q: "What is the chemical symbol for sodium?", a: "Na", e: "From its Latin name, natrium.", h: ["sodium"] },
  { cat: "Chemistry", q: "The symbol Fe stands for which element?", a: "Iron", e: "From its Latin name, ferrum.", h: ["Fe"] },
  { cat: "Chemistry", q: "Which gas makes up about 78% of the air?", a: "Nitrogen", e: "Air is about 78% nitrogen and 21% oxygen.", h: ["78%"] },
  { cat: "Chemistry", q: "Rusting needs iron, water, and which gas?", c: ["Nitrogen", "Oxygen", "Helium", "Hydrogen"], a: "B · Oxygen", m: "Iron + water + oxygen = rust.", h: ["Rusting"] },
  { cat: "Chemistry", q: "Separating alcohol from water by boiling and collecting the vapor, because they boil at different temperatures.", a: "Distillation", h: ["different temperatures", "vapor"] },
  { cat: "Chemistry", q: "Mothballs (naphthalene) slowly get smaller in a closet without melting. A solid turning straight into a gas is called?", a: "Sublimation", h: ["without melting", "straight into a gas"] },
  { cat: "Human body", q: "Which blood vessel carries OXYGEN-RICH blood from the lungs to the heart?", a: "Pulmonary vein", k: ["pulmonary veins"],
    e: "It is the only vein carrying oxygen-rich blood. The pulmonary artery carries oxygen-poor blood to the lungs.", m: "Pulmonary = lungs.", h: ["OXYGEN-RICH", "lungs to the heart"] },
  { cat: "Human body", q: "Which heart chamber pumps blood out to the whole body?", c: ["Right atrium", "Right ventricle", "Left atrium", "Left ventricle"], a: "D · Left ventricle",
    e: "It has the thickest, strongest wall because it pushes blood the farthest.", m: "Left ventricle = Largest push.", h: ["whole body"] },
  { cat: "Human body", q: "Which organ makes bile, which helps digest fat?", a: "Liver", e: "Bile is made in the liver and stored in the gallbladder.", h: ["bile", "digest fat"] },
  { cat: "Human body", q: "The hormone from the pancreas that LOWERS blood sugar.", a: "Insulin", h: ["pancreas", "LOWERS blood sugar"] },
  { cat: "Human body", q: "The part of the brain that controls balance and coordination.", a: "Cerebellum",
    e: "Cerebrum = thinking. Cerebellum = balance. Brainstem = breathing and heartbeat.", h: ["balance and coordination"] },
  { cat: "Human body", q: "Which body system fights germs and disease?", c: ["Endocrine system", "Immune system", "Skeletal system", "Excretory system"], a: "B · Immune system", h: ["fights germs"] },
  { cat: "Heredity", q: "The molecule in the nucleus that carries genetic information.", a: "DNA (deoxyribonucleic acid)", k: ["dna", "deoxyribonucleic acid"], h: ["genetic information"] },
  { cat: "Ecology", q: "Food chain: grass → grasshopper → frog → snake. What kind of consumer is the frog?", a: "Secondary consumer", k: ["secondary", "2nd order consumer", "2nd consumer", "second order consumer"],
    e: "Grasshopper eats plants (primary). Frog eats the grasshopper (secondary). Snake is tertiary.", h: ["frog"] },
  { cat: "Health", q: "Which disease is spread by the Aedes mosquito?", c: ["Malaria", "Dengue", "Tuberculosis", "Cholera"], a: "B · Dengue",
    e: "Aedes bites in the daytime and breeds in clean standing water. Malaria is spread by Anopheles.", m: "Search and destroy standing water!", h: ["Aedes"] },
  { cat: "Plants", q: "Tiny openings on the underside of leaves where carbon dioxide enters and oxygen leaves.", a: "Stomata", k: ["stoma", "stomates", "stomate"], h: ["Tiny openings", "leaves"] },
  { cat: "Ecology", q: "An orchid grows on a tree branch. The orchid benefits and the tree is not harmed. What relationship is this?", a: "Commensalism",
    e: "Mutualism: both benefit. Parasitism: one is harmed. Commensalism: one benefits, the other is unaffected.", h: ["not harmed"] },
  { cat: "Earth science", q: "The point INSIDE Earth where an earthquake starts.", a: "Focus (hypocenter)", k: ["focus", "hypocenter", "hypocentre"],
    e: "The epicenter is on the surface directly above the focus.", h: ["INSIDE Earth"] },
  { cat: "Atmosphere", q: "Which layer of the atmosphere contains the ozone layer?", a: "Stratosphere", e: "The ozone layer blocks harmful ultraviolet (UV) rays.", h: ["ozone layer"] },
  { cat: "Climate", q: "In the Philippines, El Niño usually brings:", c: ["More rain and floods", "Drought and less rain", "Snow", "Earthquakes"], a: "B · Drought and less rain",
    e: "La Niña is the opposite: more rain than normal.", m: "El Niño = dry. La Niña = wet.", h: ["El Niño"] },
  { cat: "Earth science", q: "Rock formed from layers of sand and mud pressed together over a long time.", a: "Sedimentary rock", k: ["sedimentary"],
    e: "Igneous: from cooled magma. Metamorphic: changed by heat and pressure.", h: ["layers", "pressed together"] },
  { cat: "Space", q: "A LUNAR eclipse happens when:", c: ["The Moon is between the Sun and Earth", "Earth is between the Sun and the Moon", "The Sun is between Earth and the Moon", "The Moon is at apogee"], a: "B · Earth is between the Sun and the Moon",
    e: "Earth's shadow falls on the Moon. It can only happen at full moon.", m: "Lunar = Moon gets darkened.", h: ["LUNAR"] },
  { cat: "Space", q: "What is the main reason Earth has seasons?", c: ["Its distance from the Sun", "The tilt of Earth's axis", "The Moon's pull", "Clouds"], a: "B · The tilt of Earth's axis",
    e: "The tilt (about 23.5°) makes sunlight hit each half of Earth more directly at different times of the year.", h: ["seasons"] },
  { cat: "Space", q: "What is the closest star to Earth?", a: "The Sun", k: ["sun"], e: "Trick question! The next closest is Proxima Centauri.", h: ["closest star"] },
  { cat: "Space", q: "How long does Earth take to go once around the Sun?", a: "About 365¼ days (1 year)", k: ["365", "365 days", "1 year", "one year", "365.25", "365 1/4", "365 1/4 days", "365.25 days"],
    e: "The extra ¼ day adds up to one extra day every 4 years: leap year!", h: ["once around the Sun"] },
  { cat: "Science skills", q: "A student tests how the amount of light affects plant height. The amount of light is the:", c: ["Dependent variable", "Independent variable", "Controlled variable", "Hypothesis"], a: "B · Independent variable",
    e: "Independent = what YOU change. Dependent = what you measure (plant height).", m: "I change the Independent.", h: ["amount of light", "affects"] }
];

window.CARDS.sd = [
  { cat: "Sound", q: "During a thunderstorm in Surigao, Ana sees lightning and hears the thunder 3 seconds later. Sound travels about 340 m/s. How far away was the lightning?", a: "1,020 m (about 1 km)",
    k: ["1020", "1.02 km", "1020 meters"], e: "Light arrives almost instantly. Distance = 340 × 3 = 1,020 m.", m: "Count seconds × 340 m.", h: ["3 seconds later", "340 m/s"] },
  { cat: "Human body", q: "A nurse counts a patient's pulse at the wrist: 18 beats in 15 seconds. What is the heart rate per minute?", a: "72 beats per minute", k: ["72", "72 bpm"],
    e: "15 seconds × 4 = 1 minute, so 18 × 4 = 72.", h: ["18 beats", "15 seconds"] },
  { cat: "Plants", q: "Potted plants that are watered too much wilt and die, because water fills the air spaces in the soil. Which gas can the roots no longer get?", a: "Oxygen", k: ["o2"],
    e: "Roots are alive and need oxygen for respiration.", h: ["watered too much", "air spaces"] },
  { cat: "Earth science", q: "A fisherman in Siargao feels a strong earthquake, then sees the sea suddenly pull far back from the shore. What is coming, and what should he do?", a: "A tsunami: go to high ground right away", k: ["tsunami"],
    e: "The sea pulling back is a natural warning sign. Do not go look at the exposed sea floor!", m: "Strong shaking + sea pulls back = run to high ground.", h: ["sea suddenly pull far back"] },
  { cat: "Heat", q: "Mia heats water in a pot. Warm water at the bottom rises, cooler water sinks, making a loop. What is this loop called?", a: "Convection current", k: ["convection", "convection currents"], h: ["rises", "sinks", "loop"] },
  { cat: "Electricity", q: "Leo rubs a balloon on his hair, and it sticks to the wall. What kind of electricity is this?", a: "Static electricity", k: ["static"], h: ["rubs a balloon", "sticks to the wall"] },
  { cat: "Human body", q: "A doctor sees a patient whose skin and the whites of the eyes have turned yellow (jaundice). Which organ is most likely having a problem?", a: "Liver",
    e: "A sick liver cannot clear a yellow substance (bilirubin), so it builds up in the skin and eyes.", h: ["yellow", "jaundice"] },
  { cat: "Human body", q: "An athlete breathes hard after a race. Her muscles need more oxygen and must get rid of which waste gas?", a: "Carbon dioxide", k: ["co2"], h: ["breathes hard", "waste gas"] },
  { cat: "Human body", q: "After eating very salty food, you feel thirsty and urinate less. Which organs control how much water leaves the body?", a: "Kidneys", k: ["kidney"], h: ["salty food", "urinate less"] },
  { cat: "Plants", q: "A plant on a windowsill bends toward the light. What is this response called?", a: "Phototropism", m: "Photo = light, tropism = turning.", h: ["bends toward the light"] },
  { cat: "Plants", q: "Roots always grow downward, even if a seed is planted upside down. What is this response to gravity called?", a: "Gravitropism (geotropism)", k: ["gravitropism", "geotropism"], m: "Geo = Earth.", h: ["grow downward", "gravity"] },
  { cat: "Chemistry", q: "For a science fair, a student mixes baking soda and vinegar in a bottle, and a balloon on top inflates. Which gas fills the balloon?", a: "Carbon dioxide", k: ["co2"], h: ["baking soda and vinegar", "balloon"] },
  { cat: "Chemistry", q: "Red cabbage juice turns pink in calamansi juice and green in soap solution. What is the cabbage juice acting as?", a: "An indicator (acid-base indicator)", k: ["indicator", "acid base indicator", "ph indicator"],
    e: "Indicators change color in acids and bases. Litmus paper is another indicator.", h: ["turns pink", "green", "calamansi", "soap"] },
  { cat: "Chemistry", q: "Calamansi juice is an acid. Is its pH below 7, exactly 7, or above 7?", a: "Below 7", k: ["less than 7", "lower than 7", "under 7"], m: "Acid = below 7. Base = above 7.", h: ["acid", "pH"] },
  { cat: "Chemistry", q: "Iron gates near the sea in Surigao rust much faster than those in dry inland towns. What in the sea air speeds up rusting?", a: "Salt (salty, moist air)", k: ["salt", "salt water", "salty air", "sea salt", "salt+moisture", "salt+water"],
    e: "Salt water helps the iron react with oxygen faster.", h: ["near the sea", "rust much faster"] },
  { cat: "Matter", q: "Ice cubes left on a plate on a hot day become a puddle, and later the puddle disappears. Name the two changes in order.", a: "Melting, then evaporation", k: ["melting+evaporation", "melt+evaporat"], h: ["puddle", "disappears", "in order"] },
  { cat: "Matter", q: "Early in the morning, tiny water drops appear on grass and on the outside of a cold glass. What process makes them?", a: "Condensation", e: "Water vapor in the air cools and turns into liquid.", h: ["water drops", "cold glass"] },
  { cat: "Environment", q: "Mangrove forests line the Caraga coast. How do they protect towns during typhoons?", a: "Their roots block strong waves and storm surges and hold the soil so the shore does not wash away.", self: true,
    h: ["Mangrove", "typhoons"] },
  { cat: "Space", q: "The Sun seems to rise in the east and set in the west. Which way does Earth rotate?", c: ["East to west", "West to east", "North to south", "South to north"], a: "B · West to east",
    e: "Because Earth spins toward the east, the Sun appears to move the opposite way, toward the west.", h: ["rise in the east", "set in the west"] },
  { cat: "Space", q: "About a week after new moon, you see the RIGHT half of the Moon lit in the evening sky. Which phase is this?", a: "First quarter", k: ["first quarter moon", "1st quarter"],
    e: "New moon → waxing crescent → first quarter → waxing gibbous → full moon.", h: ["week after new moon", "RIGHT half"] },
  { cat: "Earth science", q: "The Philippines lies on the Pacific Ring of Fire. Which TWO natural events are common here because of this?", a: "Earthquakes and volcanic eruptions", k: ["earthquake+volcan", "earthquake+eruption"], h: ["Pacific Ring of Fire", "TWO"] },
  { cat: "Earth science", q: "At the Philippine Trench, the Philippine Sea Plate slides UNDER another plate. What is this process called?", a: "Subduction", h: ["slides UNDER"] },
  { cat: "Heredity", q: "A pure tall pea plant (TT) is crossed with a pure short one (tt). ALL the offspring are tall. What kind of trait is tallness?", a: "Dominant", k: ["dominant trait"], e: "A dominant trait shows up even with just one copy. The hidden one is recessive.", h: ["ALL the offspring are tall"] },
  { cat: "Heredity", q: "Both parents carry one gene for albinism (Aa). What fraction of their children could have albinism (aa)?", a: "1/4 (25%)", k: ["1/4", "25%", "25", "1 in 4", "one fourth", "0.25"],
    e: "Punnett square: AA, Aa, Aa, aa. Only 1 out of 4 is aa.", h: ["Aa", "aa"] },
  { cat: "Cells", q: "Which organelle is found in plant cells but NOT in animal cells, and is where photosynthesis happens?", a: "Chloroplast", k: ["chloroplasts"], h: ["NOT in animal cells", "photosynthesis"] },
  { cat: "Health", q: "A medicine kills bacteria but does not work against the flu virus. What type of medicine is it?", a: "Antibiotic", k: ["antibiotics"], e: "Antibiotics do not kill viruses. That is why they do not cure colds or flu.", h: ["kills bacteria", "virus"] },
  { cat: "Health", q: "A child gets a measles vaccine. The vaccine trains the body to make which germ-fighting proteins?", a: "Antibodies", k: ["antibody"], h: ["vaccine", "germ-fighting proteins"] },
  { cat: "Human body", q: "Why do mountain climbers get dizzy and short of breath on very high mountains?", a: "Less oxygen in the thin air", k: ["less oxygen", "low oxygen", "thin air", "lack of oxygen", "not enough oxygen"], h: ["very high mountains"] },
  { cat: "Heat", q: "Electric wires sag on hot days and become tight on cold nights. What is this property of metals called?", a: "Thermal expansion (and contraction)", k: ["expansion", "thermal expansion", "expansion and contraction"], h: ["sag on hot days", "tight on cold nights"] },
  { cat: "Sound", q: "Bats and dolphins send out sounds and listen for the echoes to find food. What is this called?", a: "Echolocation", h: ["echoes", "find food"] },
  { cat: "Energy", q: "A farm's water pump runs on sunlight. Which device changes light energy directly into electrical energy?", a: "Solar panel (solar or photovoltaic cell)", k: ["solar panel", "solar panels", "solar cell", "photovoltaic cell", "photovoltaic"], h: ["light energy", "electrical energy"] },
  { cat: "Sound", q: "An ambulance siren sounds higher as it comes toward you and lower as it moves away. What is this effect called?", a: "Doppler effect", k: ["doppler"], h: ["higher", "lower", "moves away"] },
  { cat: "Light", q: "Your face looks upside down in the inside (hollow) part of a shiny spoon. What kind of mirror is that side?", a: "Concave mirror", k: ["concave"], m: "Concave = caves in.", h: ["upside down", "hollow"] },
  { cat: "Plants", q: "A dry seed kept in a sealed jar does not sprout. Besides warmth, which TWO things does a seed most need to start growing?", a: "Water and air (oxygen)", k: ["water+air", "water+oxygen"],
    e: "Seeds do not need light to sprout. They use food stored inside the seed.", h: ["TWO things", "sprout"] },
  { cat: "Data reading", q: "A graph shows that as ocean water temperature goes up, the number of coral reefs that turn white (bleach) also goes up. What does the graph support?",
    c: ["Warmer water is linked to more coral bleaching", "Corals make the ocean warmer", "Cold water kills corals", "Fish cause bleaching"], a: "A · Warmer water is linked to more coral bleaching",
    e: "Only say what the data shows: the two go up together.", h: ["temperature goes up", "also goes up"] }
];

window.CARDS.stf = [
  { cat: "Sound & light", q: "TRUE or FALSE: Sound travels faster than light.", c: TF, a: "B · False", e: "Light is about a million times faster. That is why you see lightning before you hear thunder." },
  { cat: "Magnets", q: "TRUE or FALSE: All metals are attracted to magnets.", c: TF, a: "B · False", e: "Iron, nickel, and cobalt are. Aluminum, copper, and gold are not.", h: ["All"] },
  { cat: "Animals", q: "TRUE or FALSE: Bats are mammals.", c: TF, a: "A · True", e: "They have fur and feed their babies milk." },
  { cat: "Animals", q: "TRUE or FALSE: A whale is a fish.", c: TF, a: "B · False", e: "Whales are mammals. They breathe air with lungs." },
  { cat: "Animals", q: "TRUE or FALSE: Spiders are insects.", c: TF, a: "B · False", e: "Spiders are arachnids with 8 legs. Insects have 6 legs." },
  { cat: "Plants", q: "TRUE or FALSE: Plants give off oxygen during photosynthesis.", c: TF, a: "A · True" },
  { cat: "Space", q: "TRUE or FALSE: The Moon makes its own light.", c: TF, a: "B · False", e: "The Moon reflects sunlight." },
  { cat: "Space", q: "TRUE or FALSE: Venus is hotter than Mercury, even though Mercury is closer to the Sun.", c: TF, a: "A · True", e: "Venus's thick carbon dioxide air traps heat (greenhouse effect)." },
  { cat: "Chemistry", q: "TRUE or FALSE: Diamond and pencil “lead” (graphite) are both made of carbon.", c: TF, a: "A · True", e: "Same element, different arrangement of atoms." },
  { cat: "Matter", q: "TRUE or FALSE: Water expands when it freezes.", c: TF, a: "A · True", e: "That is why ice floats and why a full bottle can crack in the freezer." },
  { cat: "Human body", q: "TRUE or FALSE: Veins ALWAYS carry oxygen-poor blood.", c: TF, a: "B · False", e: "The pulmonary veins carry oxygen-rich blood from the lungs.", h: ["ALWAYS"] },
  { cat: "Human body", q: "TRUE or FALSE: Adult human red blood cells have a nucleus.", c: TF, a: "B · False", e: "They lose their nucleus to make room for more hemoglobin to carry oxygen." },
  { cat: "Force", q: "TRUE or FALSE: With no air, a heavy ball falls faster than a light feather.", c: TF, a: "B · False", e: "Without air resistance, everything falls at the same rate. Astronauts showed this on the Moon.", h: ["no air"] },
  { cat: "Matter", q: "TRUE or FALSE: Salt water boils at a higher temperature than pure water.", c: TF, a: "A · True" },
  { cat: "Earth", q: "TRUE or FALSE: The Pacific is the largest ocean on Earth.", c: TF, a: "A · True" },
  { cat: "Earth science", q: "TRUE or FALSE: Scientists can predict the exact day and time of an earthquake.", c: TF, a: "B · False", e: "No one can predict earthquakes exactly. That is why we do earthquake drills." },
  { cat: "Plants", q: "TRUE or FALSE: In science, a tomato is a fruit.", c: TF, a: "A · True", e: "A fruit grows from a flower and holds seeds." },
  { cat: "Weather", q: "TRUE or FALSE: A lightning bolt is hotter than the surface of the Sun.", c: TF, a: "A · True", e: "Lightning can reach about 30,000 °C. The Sun's surface is about 5,500 °C." },
  { cat: "Sound", q: "TRUE or FALSE: Sound can travel through solids.", c: TF, a: "A · True", e: "Put your ear on a table and tap it. Sound travels even better in solids." },
  { cat: "Electricity", q: "TRUE or FALSE: Copper is a good insulator.", c: TF, a: "B · False", e: "Copper is a good CONDUCTOR. Rubber and plastic are insulators." },
  { cat: "Living things", q: "TRUE or FALSE: Mushrooms (fungi) make their own food by photosynthesis.", c: TF, a: "B · False", e: "Fungi have no chlorophyll. They absorb food from dead or living things." },
  { cat: "Space", q: "TRUE or FALSE: A solar eclipse can only happen during a new moon.", c: TF, a: "A · True", e: "The Moon must be between the Sun and Earth, which is the new moon position." },
  { cat: "Living things", q: "TRUE or FALSE: Viruses are made of cells.", c: TF, a: "B · False", e: "Viruses are not cells. They can only multiply inside living cells." },
  { cat: "Force", q: "TRUE or FALSE: Mass and weight mean the same thing.", c: TF, a: "B · False", e: "Mass = amount of matter (kg). Weight = pull of gravity on it (newtons)." },
  { cat: "Space", q: "TRUE or FALSE: Mercury is the only planet with no moon.", c: TF, a: "B · False", e: "Venus has no moon either!", h: ["only"] },
  { cat: "Human body", q: "TRUE or FALSE: A newborn baby has more bones than an adult.", c: TF, a: "A · True", e: "Babies have about 270–300 bones. Some join together as they grow, leaving 206." },
  { cat: "Animals", q: "TRUE or FALSE: Frogs can breathe through their skin.", c: TF, a: "A · True", e: "Their moist skin lets oxygen pass through." },
  { cat: "Earth science", q: "TRUE or FALSE: Magma that reaches Earth's surface is called lava.", c: TF, a: "A · True" },
  { cat: "Chemistry", q: "TRUE or FALSE: Sugar dissolving in water is a chemical change.", c: TF, a: "B · False", e: "It is a physical change. Boil off the water and you get the sugar back." },
  { cat: "Weather", q: "TRUE or FALSE: The Philippines has two main seasons, wet and dry.", c: TF, a: "A · True" }
];

window.CARDS.sph = [
  { cat: "Caraga", q: "Agusan Marsh in Agusan del Sur is protected under which international agreement for important wetlands?", a: "Ramsar Convention", k: ["ramsar"], h: ["Agusan Marsh", "wetlands"] },
  { cat: "Caraga", q: "Lolong, one of the largest crocodiles ever kept in captivity, was caught in 2011 in which province?", a: "Agusan del Sur", k: ["bunawan"], h: ["Lolong"] },
  { cat: "Caraga", q: "What kind of crocodile was Lolong?", c: ["Nile crocodile", "Saltwater crocodile", "Alligator", "Gharial"], a: "B · Saltwater crocodile", h: ["Lolong"] },
  { cat: "Caraga", q: "The Enchanted River, famous for its deep blue water, is in which town of Surigao del Sur?", a: "Hinatuan", h: ["Enchanted River"] },
  { cat: "Caraga", q: "Siargao Island is famous worldwide for surfing. What is its most famous wave called?", a: "Cloud 9", k: ["cloud nine"], h: ["Siargao", "surfing"] },
  { cat: "Caraga", q: "The Philippine Trench lies east of Caraga. About how deep is its deepest point?", c: ["About 1 km", "About 3 km", "About 10.5 km", "About 50 km"], a: "C · About 10.5 km",
    e: "Its deepest point, the Galathea Depth, is about 10,500 m. That is deeper than Mt. Everest is tall.", h: ["Philippine Trench"] },
  { cat: "Caraga", q: "Lake Mainit is shared by which two provinces?", a: "Surigao del Norte and Agusan del Norte", k: ["surigao del norte+agusan del norte"], h: ["Lake Mainit"] },
  { cat: "Caraga", q: "Nickel mined in Surigao is mixed with iron and chromium to make which rust-resistant metal used for spoons and sinks?", a: "Stainless steel", h: ["Nickel", "rust-resistant"] },
  { cat: "Caraga", q: "Tinuy-an Falls, called the “Little Niagara of the Philippines,” is in which city?", a: "Bislig City", k: ["bislig"], h: ["Tinuy-an Falls"] },
  { cat: "Philippines", q: "The Philippines' national bird lives in Mindanao forests and is one of the largest eagles in the world. Name it.", a: "Philippine eagle", k: ["monkey eating eagle", "haribon"], h: ["national bird"] },
  { cat: "Philippines", q: "A tiny primate with huge eyes, found in Bohol and parts of Mindanao.", a: "Philippine tarsier", k: ["tarsier"], h: ["huge eyes"] },
  { cat: "Philippines", q: "What does PAGASA stand for?", a: "Philippine Atmospheric, Geophysical and Astronomical Services Administration", self: true, h: ["PAGASA"] },
  { cat: "Philippines", q: "What does PHIVOLCS stand for?", a: "Philippine Institute of Volcanology and Seismology", self: true, h: ["PHIVOLCS"] },
  { cat: "Caraga", q: "Unlike most of the country, Caraga's east coast gets its heaviest rain from about November to February. Which monsoon brings it?", a: "Amihan (northeast monsoon)", k: ["amihan", "northeast monsoon"],
    e: "Caraga has a Type II climate: no real dry season, with the most rain when the amihan blows from the Pacific.", h: ["east coast", "November to February"] },
  { cat: "Caraga", q: "Which super typhoon struck Siargao and Caraga in December 2021?", a: "Odette (Rai)", k: ["odette", "rai", "typhoon odette"], h: ["December 2021"] },
  { cat: "Caraga", q: "Super Typhoon Odette made its first landfall on which island?", a: "Siargao Island", k: ["siargao"], h: ["first landfall"] },
  { cat: "Caraga", q: "After the magnitude 7.4 earthquake off Hinatuan, Surigao del Sur, on December 2, 2023, what warning did PHIVOLCS issue for coastal towns?", a: "Tsunami warning", k: ["tsunami"], h: ["Hinatuan", "coastal towns"] },
  { cat: "Philippines", q: "Mt. Apo, the highest mountain in the Philippines, is on which island?", a: "Mindanao", h: ["Mt. Apo", "highest mountain"] },
  { cat: "Philippines", q: "Mayon Volcano is famous for its almost perfect ___ shape.", a: "Cone", k: ["conical", "cone shaped"], h: ["Mayon"] },
  { cat: "Philippines", q: "Taal Volcano sits inside a lake in which province?", a: "Batangas", h: ["Taal Volcano"] },
  { cat: "Philippines", q: "In what year did Mt. Pinatubo have one of the biggest eruptions of the 20th century?", a: "1991", h: ["Mt. Pinatubo"] },
  { cat: "Philippines", q: "The International Rice Research Institute (IRRI) is in which town in Laguna?", a: "Los Baños", k: ["los banos"], h: ["IRRI"] },
  { cat: "Philippines", q: "What was the name of the Philippines' first microsatellite, launched in 2016?", a: "Diwata-1", k: ["diwata", "diwata 1"], h: ["first microsatellite"] },
  { cat: "Philippines", q: "The government agency for the Philippines' space program, created in 2019, is called?", a: "PhilSA (Philippine Space Agency)", k: ["philsa", "philippine space agency"], h: ["space program"] },
  { cat: "Caraga", q: "Ancient wooden boats found in Butuan show early Filipino shipbuilding skill. What are these boats called?", a: "Balangay", k: ["balanghay"], h: ["Butuan", "wooden boats"] }
];
